//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * Data to request an allocation of seats adjacent to a specifies seat.
 * 
 * <p>Java class for AdjacentSeatRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdjacentSeatRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RequestedTrain" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}RequestedTrainType"/>
 *         &lt;element name="Passengers" type="{http://www.uic-asso.fr/xml/passenger/02}NumberOfPassengerType"/>
 *         &lt;element name="Class" type="{http://www.uic-asso.fr/xml/passenger/02}ClassType"/>
 *         &lt;element name="CoachNumber" type="{http://www.uic-asso.fr/xml/passenger/02}CoachNumberType"/>
 *         &lt;element name="ReferencedPlace" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}PlaceNumberType"/>
 *         &lt;element name="TravelersWithCar" type="{http://www.uic-asso.fr/xml/passenger/02}TravelersWithCarType" minOccurs="0"/>
 *         &lt;element name="Tariff" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}TariffRequestType" maxOccurs="2" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="IndividualTicketing" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdjacentSeatRequestType", propOrder = {
    "requestedTrain",
    "passengers",
    "clazz",
    "coachNumber",
    "referencedPlace",
    "travelersWithCar",
    "tariff"
})
public class AdjacentSeatRequestType {

    @XmlElement(name = "RequestedTrain", required = true)
    protected RequestedTrainType requestedTrain;
    @XmlElement(name = "Passengers")
    @XmlSchemaType(name = "integer")
    protected int passengers;
    @XmlElement(name = "Class", required = true)
    protected String clazz;
    @XmlElement(name = "CoachNumber", required = true)
    protected String coachNumber;
    @XmlElement(name = "ReferencedPlace", required = true)
    protected String referencedPlace;
    @XmlElement(name = "TravelersWithCar")
    @XmlSchemaType(name = "integer")
    protected Integer travelersWithCar;
    @XmlElement(name = "Tariff")
    protected List<TariffRequestType> tariff;
    @XmlAttribute(name = "IndividualTicketing")
    protected Boolean individualTicketing;

    /**
     * Gets the value of the requestedTrain property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedTrainType }
     *     
     */
    public RequestedTrainType getRequestedTrain() {
        return requestedTrain;
    }

    /**
     * Sets the value of the requestedTrain property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedTrainType }
     *     
     */
    public void setRequestedTrain(RequestedTrainType value) {
        this.requestedTrain = value;
    }

    /**
     * Gets the value of the passengers property.
     * 
     */
    public int getPassengers() {
        return passengers;
    }

    /**
     * Sets the value of the passengers property.
     * 
     */
    public void setPassengers(int value) {
        this.passengers = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the coachNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoachNumber() {
        return coachNumber;
    }

    /**
     * Sets the value of the coachNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoachNumber(String value) {
        this.coachNumber = value;
    }

    /**
     * Gets the value of the referencedPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencedPlace() {
        return referencedPlace;
    }

    /**
     * Sets the value of the referencedPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencedPlace(String value) {
        this.referencedPlace = value;
    }

    /**
     * Gets the value of the travelersWithCar property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTravelersWithCar() {
        return travelersWithCar;
    }

    /**
     * Sets the value of the travelersWithCar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTravelersWithCar(Integer value) {
        this.travelersWithCar = value;
    }

    /**
     * Gets the value of the tariff property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tariff property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTariff().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TariffRequestType }
     * 
     * 
     */
    public List<TariffRequestType> getTariff() {
        if (tariff == null) {
            tariff = new ArrayList<TariffRequestType>();
        }
        return this.tariff;
    }

    /**
     * Gets the value of the individualTicketing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIndividualTicketing() {
        if (individualTicketing == null) {
            return false;
        } else {
            return individualTicketing;
        }
    }

    /**
     * Sets the value of the individualTicketing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIndividualTicketing(Boolean value) {
        this.individualTicketing = value;
    }

}
