//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

import st4rt.convertor.empire.annotation.Link;
import st4rt.convertor.empire.annotation.RdfProperty;


/**
 * Range or set of allocated places. The allowed number of chiled elements has been choosen to be in line with the definition of the allocated places in leaflet 918.
 *
 * <p>Java class for AllocatedPlacesType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AllocatedPlacesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="8">
 *           &lt;element name="Range" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}PlaceRangeType"/>
 *           &lt;element name="Place" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}PlaceType" maxOccurs="2"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AllocatedPlacesType", propOrder = {
        "rangeOrPlace"
})

//@RdfsClass("product:AllocatedFacilities")
public class AllocatedPlacesType {/*implements SupportsRdfId {

    @XmlTransient
    private SupportsRdfId mIdSupport = new SupportsRdfIdImpl();

    public RdfKey getRdfId() {
        return mIdSupport.getRdfId();
    }

    public void setRdfId(RdfKey theId) {
        mIdSupport.setRdfId(theId);
    }*/

    @XmlElements({
            @XmlElement(name = "Range", type = PlaceRangeType.class),
            @XmlElement(name = "Place", type = PlaceType.class)
    })
    @RdfProperty(links = {
            @Link(propertyName = "travel:hasItineraryOffer", nodeType = Link.NodeType.Shared, sharedID = "IDforItineraryOffer"),
            @Link(propertyName = "st4rt:hasItineraryOfferItem", nodeType = Link.NodeType.Shared, sharedID = "IDforItineraryOfferItem"),
            @Link(propertyName = "shopping:hasOfferedProduct", nodeType = Link.NodeType.Shared, sharedID = "IDforOfferedProduct"),
            @Link(propertyName = "product:hasFareProductDescription", nodeType = Link.NodeType.Shared, sharedID = "IDforFareProductDescription"),
            @Link(propertyName = "product:hasAllocatedFacilities", nodeType = Link.NodeType.Shared, sharedID = "IDforAllocatedFAcility")},
            propertyName = "product:hasFacility")

    protected List<Object> rangeOrPlace;

    /**
     * Gets the value of the rangeOrPlace property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rangeOrPlace property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRangeOrPlace().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlaceRangeType }
     * {@link PlaceType }
     *
     *
     */
    public List<Object> getRangeOrPlace() {
        if (rangeOrPlace == null) {
            rangeOrPlace = new ArrayList<Object>();
        }
        return this.rangeOrPlace;
    }

    public void setRangeOrPlace(List<Object> rangeOrPlace) {
        this.getRangeOrPlace().add(rangeOrPlace);
    }

}
