//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * All data required to request the available offers on a train.
 * 
 * <p>Java class for AvailabilityRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AvailabilityRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RequestedTrain" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}RequestedTrainType"/>
 *         &lt;element name="Service" type="{http://www.uic-asso.fr/xml/passenger/02}ServiceType"/>
 *         &lt;element name="Coach" type="{http://www.uic-asso.fr/xml/passenger/02}CoachNumberType" minOccurs="0"/>
 *         &lt;element name="Tariff" type="{http://www.uic-asso.fr/xml/passenger/02}TariffCodeUICType" maxOccurs="8" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SequenceId" use="required" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}SequenceIdType" />
 *       &lt;attribute name="WithPrice" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AvailabilityRequestType", propOrder = {
    "requestedTrain",
    "service",
    "coach",
    "tariff"
})
public class AvailabilityRequestType {

    @XmlElement(name = "RequestedTrain", required = true)
    protected RequestedTrainType requestedTrain;
    @XmlElement(name = "Service", required = true)
    protected BigInteger service;
    @XmlElement(name = "Coach")
    protected String coach;
    @XmlElement(name = "Tariff")
    protected List<TariffCodeUICType> tariff;
    @XmlAttribute(name = "SequenceId", required = true)
    protected int sequenceId;
    @XmlAttribute(name = "WithPrice")
    protected Boolean withPrice;

    /**
     * Gets the value of the requestedTrain property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedTrainType }
     *     
     */
    public RequestedTrainType getRequestedTrain() {
        return requestedTrain;
    }

    /**
     * Sets the value of the requestedTrain property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedTrainType }
     *     
     */
    public void setRequestedTrain(RequestedTrainType value) {
        this.requestedTrain = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setService(BigInteger value) {
        this.service = value;
    }

    /**
     * Gets the value of the coach property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoach() {
        return coach;
    }

    /**
     * Sets the value of the coach property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoach(String value) {
        this.coach = value;
    }

    /**
     * Gets the value of the tariff property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tariff property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTariff().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TariffCodeUICType }
     * 
     * 
     */
    public List<TariffCodeUICType> getTariff() {
        if (tariff == null) {
            tariff = new ArrayList<TariffCodeUICType>();
        }
        return this.tariff;
    }

    /**
     * Gets the value of the sequenceId property.
     * 
     */
    public int getSequenceId() {
        return sequenceId;
    }

    /**
     * Sets the value of the sequenceId property.
     * 
     */
    public void setSequenceId(int value) {
        this.sequenceId = value;
    }

    /**
     * Gets the value of the withPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isWithPrice() {
        if (withPrice == null) {
            return true;
        } else {
            return withPrice;
        }
    }

    /**
     * Sets the value of the withPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWithPrice(Boolean value) {
        this.withPrice = value;
    }

}
