//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * Available offer
 * 
 * <p>Java class for AvailableOfferType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AvailableOfferType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Tariff" type="{http://www.uic-asso.fr/xml/passenger/02}TariffCodeUICType"/>
 *         &lt;element name="Scope" type="{http://www.uic-asso.fr/xml/passenger/02}PriceScopeType" minOccurs="0"/>
 *         &lt;element name="Amount" type="{http://www.uic-asso.fr/xml/passenger/02}AmountEuroCentType" minOccurs="0"/>
 *         &lt;element name="Flexibility" type="{http://www.uic-asso.fr/xml/passenger/02}PriceFlexibilityType" minOccurs="0"/>
 *         &lt;element name="Stability" type="{http://www.uic-asso.fr/xml/passenger/02}PriceStabilityType" minOccurs="0"/>
 *         &lt;element name="Description" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;choice maxOccurs="2">
 *           &lt;element name="Passengers" type="{http://www.uic-asso.fr/xml/passenger/02}NumberOfPassengerType"/>
 *           &lt;element name="Smokers" type="{http://www.uic-asso.fr/xml/passenger/02}NumberOfPassengerType"/>
 *           &lt;element name="NonSmokers" type="{http://www.uic-asso.fr/xml/passenger/02}NumberOfPassengerType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="Type" use="required" type="{http://www.uic-asso.fr/xml/passenger/02}PriceTypeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AvailableOfferType", propOrder = {
    "tariff",
    "scope",
    "amount",
    "flexibility",
    "stability",
    "description",
    "passengersOrSmokersOrNonSmokers"
})
public class AvailableOfferType {

    @XmlElement(name = "Tariff", required = true)
    protected TariffCodeUICType tariff;
    @XmlElement(name = "Scope")
    protected BigInteger scope;
    @XmlElement(name = "Amount")
    @XmlSchemaType(name = "integer")
    protected Integer amount;
    @XmlElement(name = "Flexibility")
    @XmlSchemaType(name = "token")
    protected PriceFlexibilityType flexibility;
    @XmlElement(name = "Stability")
    protected BigInteger stability;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElementRefs({
        @XmlElementRef(name = "Passengers", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Smokers", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "NonSmokers", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<Integer>> passengersOrSmokersOrNonSmokers;
    @XmlAttribute(name = "Type", required = true)
    protected BigInteger type;

    /**
     * Gets the value of the tariff property.
     * 
     * @return
     *     possible object is
     *     {@link TariffCodeUICType }
     *     
     */
    public TariffCodeUICType getTariff() {
        return tariff;
    }

    /**
     * Sets the value of the tariff property.
     * 
     * @param value
     *     allowed object is
     *     {@link TariffCodeUICType }
     *     
     */
    public void setTariff(TariffCodeUICType value) {
        this.tariff = value;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getScope() {
        return scope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setScope(BigInteger value) {
        this.scope = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAmount(Integer value) {
        this.amount = value;
    }

    /**
     * Gets the value of the flexibility property.
     * 
     * @return
     *     possible object is
     *     {@link PriceFlexibilityType }
     *     
     */
    public PriceFlexibilityType getFlexibility() {
        return flexibility;
    }

    /**
     * Sets the value of the flexibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceFlexibilityType }
     *     
     */
    public void setFlexibility(PriceFlexibilityType value) {
        this.flexibility = value;
    }

    /**
     * Gets the value of the stability property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStability() {
        return stability;
    }

    /**
     * Sets the value of the stability property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStability(BigInteger value) {
        this.stability = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the passengersOrSmokersOrNonSmokers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the passengersOrSmokersOrNonSmokers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPassengersOrSmokersOrNonSmokers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * 
     */
    public List<JAXBElement<Integer>> getPassengersOrSmokersOrNonSmokers() {
        if (passengersOrSmokersOrNonSmokers == null) {
            passengersOrSmokersOrNonSmokers = new ArrayList<JAXBElement<Integer>>();
        }
        return this.passengersOrSmokersOrNonSmokers;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setType(BigInteger value) {
        this.type = value;
    }

}
