//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * Data to describe the offer booked.
 * 
 * <p>Java class for BookedOfferType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BookedOfferType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Price" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}PriceType" minOccurs="0"/>
 *         &lt;element name="Supplements" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}SupplementType" minOccurs="0"/>
 *         &lt;element name="CancelationFees" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CancelationLimit" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Reason" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}ReasonForCancellationType" minOccurs="0"/>
 *                             &lt;element name="TimeLimit" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BookedOfferType", propOrder = {
    "price",
    "supplements",
    "cancelationFees"
})
@XmlSeeAlso({
    RefundType.class
})
public class BookedOfferType {

    @XmlElement(name = "Price")
    protected PriceType price;
    @XmlElement(name = "Supplements")
    protected SupplementType supplements;
    @XmlElement(name = "CancelationFees")
    protected BookedOfferType.CancelationFees cancelationFees;

    /**
     * Gets the value of the price property.
     *
     * @return
     *     possible object is
     *     {@link PriceType }
     *
     */
    public PriceType getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     *
     * @param value
     *     allowed object is
     *     {@link PriceType }
     *
     */
    public void setPrice(PriceType value) {
        this.price = value;
    }

    /**
     * Gets the value of the supplements property.
     *
     * @return
     *     possible object is
     *     {@link SupplementType }
     *
     */
    public SupplementType getSupplements() {
        return supplements;
    }

    /**
     * Sets the value of the supplements property.
     *
     * @param value
     *     allowed object is
     *     {@link SupplementType }
     *
     */
    public void setSupplements(SupplementType value) {
        this.supplements = value;
    }

    /**
     * Gets the value of the cancelationFees property.
     *
     * @return
     *     possible object is
     *     {@link BookedOfferType.CancelationFees }
     *
     */
    public BookedOfferType.CancelationFees getCancelationFees() {
        return cancelationFees;
    }

    /**
     * Sets the value of the cancelationFees property.
     *
     * @param value
     *     allowed object is
     *     {@link BookedOfferType.CancelationFees }
     *
     */
    public void setCancelationFees(BookedOfferType.CancelationFees value) {
        this.cancelationFees = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CancelationLimit" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Reason" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}ReasonForCancellationType" minOccurs="0"/>
     *                   &lt;element name="TimeLimit" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cancelationLimit"
    })
    public static class CancelationFees {

        @XmlElement(name = "CancelationLimit", required = true)
        protected List<CancelationLimit> cancelationLimit;

        /**
         * Gets the value of the cancelationLimit property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cancelationLimit property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCancelationLimit().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BookedOfferType.CancelationFees.CancelationLimit }
         *
         *
         */
        public List<CancelationLimit> getCancelationLimit() {
            if (cancelationLimit == null) {
                cancelationLimit = new ArrayList<CancelationLimit>();
            }
            return this.cancelationLimit;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Reason" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}ReasonForCancellationType" minOccurs="0"/>
         *         &lt;element name="TimeLimit" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "reason",
            "timeLimit"
        })
        public static class CancelationLimit {

            @XmlElement(name = "Reason")
            protected BigInteger reason;
            @XmlElement(name = "TimeLimit", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar timeLimit;

            /**
             * Gets the value of the reason property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getReason() {
                return reason;
            }

            /**
             * Sets the value of the reason property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setReason(BigInteger value) {
                this.reason = value;
            }

            /**
             * Gets the value of the timeLimit property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getTimeLimit() {
                return timeLimit;
            }

            /**
             * Sets the value of the timeLimit property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setTimeLimit(XMLGregorianCalendar value) {
                this.timeLimit = value;
            }

        }

    }

}
