//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import st4rt.convertor.empire.annotation.SupportsRdfId;
import st4rt.convertor.empire.annotation.SupportsRdfIdImpl;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for LocationSubsidiaryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocationSubsidiaryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="LocationSubsidiaryTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocationSubsidiaryType", namespace = "http://www.uic-asso.fr/xml/passenger/02")
public class LocationSubsidiaryType implements SupportsRdfId {

    @XmlTransient
    private SupportsRdfId mIdSupport = new SupportsRdfIdImpl();

    public RdfKey getRdfId() {
        return mIdSupport.getRdfId();
    }

    public void setRdfId(RdfKey theId) {
        mIdSupport.setRdfId(theId);
    }

    @XmlAttribute(name = "LocationSubsidiaryTypeCode")
    protected String locationSubsidiaryTypeCode;

    /**
     * Gets the value of the locationSubsidiaryTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationSubsidiaryTypeCode() {
        return locationSubsidiaryTypeCode;
    }

    /**
     * Sets the value of the locationSubsidiaryTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationSubsidiaryTypeCode(String value) {
        this.locationSubsidiaryTypeCode = value;
    }

}
