//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * Data to request the booking of a meal.
 * 
 * <p>Java class for MealBookingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MealBookingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AllocatedTrain" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}AllocatedTrainType"/>
 *         &lt;element name="Meals" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}BookedMealType" maxOccurs="3"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MealBookingType", propOrder = {
    "allocatedTrain",
    "meals"
})
public class MealBookingType {

    @XmlElement(name = "AllocatedTrain", required = true)
    protected AllocatedTrainType allocatedTrain;
    @XmlElement(name = "Meals", required = true)
    protected List<BookedMealType> meals;

    /**
     * Gets the value of the allocatedTrain property.
     * 
     * @return
     *     possible object is
     *     {@link AllocatedTrainType }
     *     
     */
    public AllocatedTrainType getAllocatedTrain() {
        return allocatedTrain;
    }

    /**
     * Sets the value of the allocatedTrain property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllocatedTrainType }
     *     
     */
    public void setAllocatedTrain(AllocatedTrainType value) {
        this.allocatedTrain = value;
    }

    /**
     * Gets the value of the meals property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meals property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeals().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BookedMealType }
     * 
     * 
     */
    public List<BookedMealType> getMeals() {
        if (meals == null) {
            meals = new ArrayList<BookedMealType>();
        }
        return this.meals;
    }

}
