//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * Data to be returned, if a request can not be answered by the desired allocation of train information.
 * 
 * <p>Java class for NegativeReplyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NegativeReplyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="AlternativeService" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}AlternativeServiceCodeType" maxOccurs="9" minOccurs="0"/>
 *         &lt;element name="AlternativeTrain" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Train" type="{http://www.uic-asso.fr/xml/passenger/02}TrainNumberType"/>
 *                   &lt;element name="Departure" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="Arrival" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="ServiceBrand" type="{http://www.uic-asso.fr/xml/passenger/02}ServiceBrandInformationType"/>
 *                   &lt;element name="AlternativeService" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}AlternativeServiceCodeType" maxOccurs="9" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AlternativeSystem" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="System" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}ReservationSystemType"/>
 *                   &lt;element name="Train" type="{http://www.uic-asso.fr/xml/passenger/02}TrainNumberType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute name="SequenceId" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}SequenceIdType" />
 *       &lt;attribute name="ReplyCode" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}ReplyCodeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NegativeReplyType", propOrder = {
    "alternativeService",
    "alternativeTrain",
    "alternativeSystem"
})
public class NegativeReplyType {

    @XmlElement(name = "AlternativeService")
    protected List<String> alternativeService;
    @XmlElement(name = "AlternativeTrain")
    protected NegativeReplyType.AlternativeTrain alternativeTrain;
    @XmlElement(name = "AlternativeSystem")
    protected NegativeReplyType.AlternativeSystem alternativeSystem;
    @XmlAttribute(name = "SequenceId")
    protected Integer sequenceId;
    @XmlAttribute(name = "ReplyCode")
    protected Integer replyCode;

    /**
     * Gets the value of the alternativeService property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alternativeService property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlternativeService().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getAlternativeService() {
        if (alternativeService == null) {
            alternativeService = new ArrayList<String>();
        }
        return this.alternativeService;
    }

    /**
     * Gets the value of the alternativeTrain property.
     *
     * @return
     *     possible object is
     *     {@link NegativeReplyType.AlternativeTrain }
     *
     */
    public NegativeReplyType.AlternativeTrain getAlternativeTrain() {
        return alternativeTrain;
    }

    /**
     * Sets the value of the alternativeTrain property.
     *
     * @param value
     *     allowed object is
     *     {@link NegativeReplyType.AlternativeTrain }
     *
     */
    public void setAlternativeTrain(NegativeReplyType.AlternativeTrain value) {
        this.alternativeTrain = value;
    }

    /**
     * Gets the value of the alternativeSystem property.
     *
     * @return
     *     possible object is
     *     {@link NegativeReplyType.AlternativeSystem }
     *
     */
    public NegativeReplyType.AlternativeSystem getAlternativeSystem() {
        return alternativeSystem;
    }

    /**
     * Sets the value of the alternativeSystem property.
     *
     * @param value
     *     allowed object is
     *     {@link NegativeReplyType.AlternativeSystem }
     *
     */
    public void setAlternativeSystem(NegativeReplyType.AlternativeSystem value) {
        this.alternativeSystem = value;
    }

    /**
     * Gets the value of the sequenceId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSequenceId() {
        return sequenceId;
    }

    /**
     * Sets the value of the sequenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSequenceId(Integer value) {
        this.sequenceId = value;
    }

    /**
     * Gets the value of the replyCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReplyCode() {
        return replyCode;
    }

    /**
     * Sets the value of the replyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReplyCode(Integer value) {
        this.replyCode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="System" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}ReservationSystemType"/>
     *         &lt;element name="Train" type="{http://www.uic-asso.fr/xml/passenger/02}TrainNumberType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "system",
        "train"
    })
    public static class AlternativeSystem {

        @XmlElement(name = "System")
        protected int system;
        @XmlElement(name = "Train")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String train;

        /**
         * Gets the value of the system property.
         * 
         */
        public int getSystem() {
            return system;
        }

        /**
         * Sets the value of the system property.
         * 
         */
        public void setSystem(int value) {
            this.system = value;
        }

        /**
         * Gets the value of the train property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrain() {
            return train;
        }

        /**
         * Sets the value of the train property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrain(String value) {
            this.train = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Train" type="{http://www.uic-asso.fr/xml/passenger/02}TrainNumberType"/>
     *         &lt;element name="Departure" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="Arrival" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="ServiceBrand" type="{http://www.uic-asso.fr/xml/passenger/02}ServiceBrandInformationType"/>
     *         &lt;element name="AlternativeService" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}AlternativeServiceCodeType" maxOccurs="9" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "train",
        "departure",
        "arrival",
        "serviceBrand",
        "alternativeService"
    })
    public static class AlternativeTrain {

        @XmlElement(name = "Train", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String train;
        @XmlElement(name = "Departure", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar departure;
        @XmlElement(name = "Arrival", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar arrival;
        @XmlElement(name = "ServiceBrand", required = true)
        protected ServiceBrandInformationType serviceBrand;
        @XmlElement(name = "AlternativeService")
        protected List<String> alternativeService;

        /**
         * Gets the value of the train property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrain() {
            return train;
        }

        /**
         * Sets the value of the train property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrain(String value) {
            this.train = value;
        }

        /**
         * Gets the value of the departure property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDeparture() {
            return departure;
        }

        /**
         * Sets the value of the departure property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDeparture(XMLGregorianCalendar value) {
            this.departure = value;
        }

        /**
         * Gets the value of the arrival property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getArrival() {
            return arrival;
        }

        /**
         * Sets the value of the arrival property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setArrival(XMLGregorianCalendar value) {
            this.arrival = value;
        }

        /**
         * Gets the value of the serviceBrand property.
         * 
         * @return
         *     possible object is
         *     {@link ServiceBrandInformationType }
         *     
         */
        public ServiceBrandInformationType getServiceBrand() {
            return serviceBrand;
        }

        /**
         * Sets the value of the serviceBrand property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServiceBrandInformationType }
         *     
         */
        public void setServiceBrand(ServiceBrandInformationType value) {
            this.serviceBrand = value;
        }

        /**
         * Gets the value of the alternativeService property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the alternativeService property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAlternativeService().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAlternativeService() {
            if (alternativeService == null) {
                alternativeService = new ArrayList<String>();
            }
            return this.alternativeService;
        }

    }

}
