//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import st4rt.convertor.empire.annotation.*;
import st4rt.convertor.empire.annotation.Query.QueryType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * Number and type of a place.
 *
 * <p>Java class for PlaceType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PlaceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Place" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}PlaceNumberType" />
 *       &lt;attribute name="Code" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}PlaceCodeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlaceType")
@RdfsClass("product:Facility")
@Queries({

        @Query(name="918Reply_LF_AccomodationType"),

})
public class PlaceType implements SupportsRdfId {

    @XmlTransient
    private SupportsRdfId mIdSupport = new SupportsRdfIdImpl();

    public RdfKey getRdfId() {
        return mIdSupport.getRdfId();
    }

    public void setRdfId(RdfKey theId) {
        mIdSupport.setRdfId(theId);
    }

    @XmlAttribute(name = "Place")
    @RdfProperty(propertyName = "product:hasPlaceNo")
    protected String place;

    @XmlAttribute(name = "Code")
    @RdfProperty(propertyName = "st4rt:hasCVValue")
    @Query(name="918Reply_LW_AccomodationType",outputs= {"accommodationType"},type=QueryType.Lowering)
    protected String code;

    /**
     * Gets the value of the place property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPlace() {
        return place;
    }

    /**
     * Sets the value of the place property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPlace(String value) {
        this.place = value;
    }

    /**
     * Gets the value of the code property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCode(String value) {
        this.code = value;
    }

}
