//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import javax.xml.bind.annotation.*;


/**
 * Customer request for a specific location of a place.
 * 
 * <p>Java class for PositionOfPlaceRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PositionOfPlaceRequestType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.uic-asso.fr/xml/passenger/reservation/01>NumberOfPositionsType">
 *       &lt;attribute name="Mandatory" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="Position" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}PositionOfPlaceType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PositionOfPlaceRequestType", propOrder = {
    "value"
})
public class PositionOfPlaceRequestType {

    @XmlValue
    protected int value;
    @XmlAttribute(name = "Mandatory")
    protected Boolean mandatory;
    @XmlAttribute(name = "Position")
    protected PositionOfPlaceType position;

    /**
     * Gets the value of the value property.
     * 
     */
    public int getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(int value) {
        this.value = value;
    }

    /**
     * Gets the value of the mandatory property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isMandatory() {
        if (mandatory == null) {
            return false;
        } else {
            return mandatory;
        }
    }

    /**
     * Sets the value of the mandatory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMandatory(Boolean value) {
        this.mandatory = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link PositionOfPlaceType }
     *     
     */
    public PositionOfPlaceType getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionOfPlaceType }
     *     
     */
    public void setPosition(PositionOfPlaceType value) {
        this.position = value;
    }

}
