//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import st4rt.convertor.empire.annotation.Link;
import st4rt.convertor.empire.annotation.RdfProperty;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * This element defines a total price which might be the sum of prices per tariff
 * 
 * <p>Java class for PriceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PriceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Amount" type="{http://www.uic-asso.fr/xml/passenger/02}AmountEuroCentType"/>
 *         &lt;element name="PartialPrice" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}PartialPriceType" maxOccurs="3" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Type" type="{http://www.uic-asso.fr/xml/passenger/02}PriceTypeType" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PriceType", propOrder = {
    "amount",
    "partialPrice"
})
public class PriceType {

    @XmlElement(name = "Amount")
    @XmlSchemaType(name = "integer")
    @RdfProperty(links = {
            @Link(propertyName = "travel:hasItineraryOffer", nodeType = Link.NodeType.Shared, sharedID = "IDforItineraryOffer"),
            @Link(propertyName = "st4rt:hasItineraryOfferItem", nodeType = Link.NodeType.Shared, sharedID = "IDforItineraryOfferItem"),
            @Link(propertyName = "shopping:hasGlobalQuotation", nodeType = Link.NodeType.Shared, sharedID = "IDforGlobalQuotation"),
            @Link(propertyName = "shopping:hasPrice", nodeType = Link.NodeType.Shared, sharedID = "IDforPrice")},
            propertyName = "shopping:hasAmount")
    protected int amount;
    @XmlElement(name = "PartialPrice")
    protected List<PartialPriceType> partialPrice;
    @XmlAttribute(name = "Type")
    protected BigInteger type;

    /**
     * Gets the value of the amount property.
     * 
     */
    public int getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     */
    public void setAmount(int value) {
        this.amount = value;
    }

    /**
     * Gets the value of the partialPrice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partialPrice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartialPrice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartialPriceType }
     * 
     * 
     */
    public List<PartialPriceType> getPartialPrice() {
        if (partialPrice == null) {
            partialPrice = new ArrayList<PartialPriceType>();
        }
        return this.partialPrice;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getType() {
        if (type == null) {
            return new BigInteger("0");
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setType(BigInteger value) {
        this.type = value;
    }

}
