//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import st4rt.convertor.empire.annotation.Link;
import st4rt.convertor.empire.annotation.Query;
import st4rt.convertor.empire.annotation.RdfProperty;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Reference of a reservation. The reference is unique only when combined with travel date and train number.
 * 
 * <p>Java class for ReferenceNumberType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReferenceNumberType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="AllocatingSystem" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}ReservationSystemType" />
 *       &lt;attribute name="LocalReference" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}LocalReferenceNumberType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReferenceNumberType")
public class ReferenceNumberType {

    @XmlAttribute(name = "AllocatingSystem")
    @Query(name = "918_LW_AllocatingSystem", outputs = {"allocatingSystem"}, type = Query.QueryType.Lowering)
    protected Integer allocatingSystem;
    @XmlAttribute(name = "LocalReference")
    @RdfProperty(links = {
            @Link(propertyName = "travel:hasItineraryOffer", nodeType = Link.NodeType.Shared, sharedID = "IDforItineraryOffer"),
            @Link(propertyName = "mobility:hasBookedItineraryOffer", nodeType = Link.NodeType.Shared, sharedID = "IDforBookedItineraryOffer")},
            propertyName = "mobility:hasReference")
    @Query(name = "918_LW_LocalReference", outputs = {"localReference"}, type = Query.QueryType.Lowering)
    protected String localReference;

    /**
     * Gets the value of the allocatingSystem property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAllocatingSystem() {
        return allocatingSystem;
    }

    /**
     * Sets the value of the allocatingSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAllocatingSystem(Integer value) {
        this.allocatingSystem = value;
    }

    /**
     * Gets the value of the localReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalReference() {
        return localReference;
    }

    /**
     * Sets the value of the localReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalReference(String value) {
        this.localReference = value;
    }

}
