//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * Data to request an allocation of a restaurant seat.
 * 
 * <p>Java class for RestaurantSeatRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RestaurantSeatRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RequestedTrain" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}RequestedTrainType"/>
 *         &lt;element name="Meals" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}RequestedMealType" maxOccurs="3"/>
 *       &lt;/sequence>
 *       &lt;attribute name="IndividualTicketing" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RestaurantSeatRequestType", propOrder = {
    "requestedTrain",
    "meals"
})
public class RestaurantSeatRequestType {

    @XmlElement(name = "RequestedTrain", required = true)
    protected RequestedTrainType requestedTrain;
    @XmlElement(name = "Meals", required = true)
    protected List<RequestedMealType> meals;
    @XmlAttribute(name = "IndividualTicketing")
    protected Boolean individualTicketing;

    /**
     * Gets the value of the requestedTrain property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedTrainType }
     *     
     */
    public RequestedTrainType getRequestedTrain() {
        return requestedTrain;
    }

    /**
     * Sets the value of the requestedTrain property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedTrainType }
     *     
     */
    public void setRequestedTrain(RequestedTrainType value) {
        this.requestedTrain = value;
    }

    /**
     * Gets the value of the meals property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meals property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeals().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequestedMealType }
     * 
     * 
     */
    public List<RequestedMealType> getMeals() {
        if (meals == null) {
            meals = new ArrayList<RequestedMealType>();
        }
        return this.meals;
    }

    /**
     * Gets the value of the individualTicketing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIndividualTicketing() {
        if (individualTicketing == null) {
            return false;
        } else {
            return individualTicketing;
        }
    }

    /**
     * Sets the value of the individualTicketing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIndividualTicketing(Boolean value) {
        this.individualTicketing = value;
    }

}
