//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;


/**
 * Confirmation of a erquested rollback.
 * 
 * <p>Java class for RollbackBookingConfirmationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RollbackBookingConfirmationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Train" type="{http://www.uic-asso.fr/xml/passenger/02}TrainNumberType"/>
 *         &lt;element name="DepartureDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Reference" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}ReferenceNumberType"/>
 *         &lt;element name="OriginalDialogNumber" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}DialogueNumberType"/>
 *         &lt;element name="Service" type="{http://www.uic-asso.fr/xml/passenger/02}ServiceType"/>
 *         &lt;element name="ReferenceBreakfast" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}ReferenceNumberType" minOccurs="0"/>
 *         &lt;element name="ReferenceLunch" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}ReferenceNumberType" minOccurs="0"/>
 *         &lt;element name="ReferenceDinner" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}ReferenceNumberType" minOccurs="0"/>
 *         &lt;element name="Price" type="{http://www.uic-asso.fr/xml/passenger/02}AmountEuroCentType"/>
 *         &lt;element name="PriceOfBreakfast" type="{http://www.uic-asso.fr/xml/passenger/02}AmountEuroCentType" minOccurs="0"/>
 *         &lt;element name="PriceOfLunch" type="{http://www.uic-asso.fr/xml/passenger/02}AmountEuroCentType" minOccurs="0"/>
 *         &lt;element name="PriceOfDinner" type="{http://www.uic-asso.fr/xml/passenger/02}AmountEuroCentType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RollbackBookingConfirmationType", propOrder = {
    "train",
    "departureDate",
    "reference",
    "originalDialogNumber",
    "service",
    "referenceBreakfast",
    "referenceLunch",
    "referenceDinner",
    "price",
    "priceOfBreakfast",
    "priceOfLunch",
    "priceOfDinner"
})
public class RollbackBookingConfirmationType {

    @XmlElement(name = "Train", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String train;
    @XmlElement(name = "DepartureDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar departureDate;
    @XmlElement(name = "Reference", required = true)
    protected ReferenceNumberType reference;
    @XmlElement(name = "OriginalDialogNumber")
    @XmlSchemaType(name = "integer")
    protected int originalDialogNumber;
    @XmlElement(name = "Service", required = true)
    protected BigInteger service;
    @XmlElement(name = "ReferenceBreakfast")
    protected ReferenceNumberType referenceBreakfast;
    @XmlElement(name = "ReferenceLunch")
    protected ReferenceNumberType referenceLunch;
    @XmlElement(name = "ReferenceDinner")
    protected ReferenceNumberType referenceDinner;
    @XmlElement(name = "Price")
    @XmlSchemaType(name = "integer")
    protected int price;
    @XmlElement(name = "PriceOfBreakfast")
    @XmlSchemaType(name = "integer")
    protected Integer priceOfBreakfast;
    @XmlElement(name = "PriceOfLunch")
    @XmlSchemaType(name = "integer")
    protected Integer priceOfLunch;
    @XmlElement(name = "PriceOfDinner")
    @XmlSchemaType(name = "integer")
    protected Integer priceOfDinner;

    /**
     * Gets the value of the train property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrain() {
        return train;
    }

    /**
     * Sets the value of the train property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrain(String value) {
        this.train = value;
    }

    /**
     * Gets the value of the departureDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDepartureDate() {
        return departureDate;
    }

    /**
     * Sets the value of the departureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDepartureDate(XMLGregorianCalendar value) {
        this.departureDate = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceNumberType }
     *     
     */
    public ReferenceNumberType getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceNumberType }
     *     
     */
    public void setReference(ReferenceNumberType value) {
        this.reference = value;
    }

    /**
     * Gets the value of the originalDialogNumber property.
     * 
     */
    public int getOriginalDialogNumber() {
        return originalDialogNumber;
    }

    /**
     * Sets the value of the originalDialogNumber property.
     * 
     */
    public void setOriginalDialogNumber(int value) {
        this.originalDialogNumber = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setService(BigInteger value) {
        this.service = value;
    }

    /**
     * Gets the value of the referenceBreakfast property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceNumberType }
     *     
     */
    public ReferenceNumberType getReferenceBreakfast() {
        return referenceBreakfast;
    }

    /**
     * Sets the value of the referenceBreakfast property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceNumberType }
     *     
     */
    public void setReferenceBreakfast(ReferenceNumberType value) {
        this.referenceBreakfast = value;
    }

    /**
     * Gets the value of the referenceLunch property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceNumberType }
     *     
     */
    public ReferenceNumberType getReferenceLunch() {
        return referenceLunch;
    }

    /**
     * Sets the value of the referenceLunch property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceNumberType }
     *     
     */
    public void setReferenceLunch(ReferenceNumberType value) {
        this.referenceLunch = value;
    }

    /**
     * Gets the value of the referenceDinner property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceNumberType }
     *     
     */
    public ReferenceNumberType getReferenceDinner() {
        return referenceDinner;
    }

    /**
     * Sets the value of the referenceDinner property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceNumberType }
     *     
     */
    public void setReferenceDinner(ReferenceNumberType value) {
        this.referenceDinner = value;
    }

    /**
     * Gets the value of the price property.
     * 
     */
    public int getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     */
    public void setPrice(int value) {
        this.price = value;
    }

    /**
     * Gets the value of the priceOfBreakfast property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPriceOfBreakfast() {
        return priceOfBreakfast;
    }

    /**
     * Sets the value of the priceOfBreakfast property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPriceOfBreakfast(Integer value) {
        this.priceOfBreakfast = value;
    }

    /**
     * Gets the value of the priceOfLunch property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPriceOfLunch() {
        return priceOfLunch;
    }

    /**
     * Sets the value of the priceOfLunch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPriceOfLunch(Integer value) {
        this.priceOfLunch = value;
    }

    /**
     * Gets the value of the priceOfDinner property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPriceOfDinner() {
        return priceOfDinner;
    }

    /**
     * Sets the value of the priceOfDinner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPriceOfDinner(Integer value) {
        this.priceOfDinner = value;
    }

}
