//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * Allocation of seats.
 * 
 * <p>Java class for SeatAllocationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SeatAllocationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AllocatedTrain" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}AllocatedTrainType"/>
 *         &lt;element name="Passengers" type="{http://www.uic-asso.fr/xml/passenger/02}NumberOfPassengerType"/>
 *         &lt;element name="Class" type="{http://www.uic-asso.fr/xml/passenger/02}ClassType"/>
 *         &lt;element name="CoachNumber" type="{http://www.uic-asso.fr/xml/passenger/02}CoachNumberType"/>
 *         &lt;element name="CoachType" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}AllocatedCoachTypeType" minOccurs="0"/>
 *         &lt;element name="CompartmentType" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}AllocatedCompartmentTypeType" minOccurs="0"/>
 *         &lt;element name="Contingent" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}AllocatedContingentTypeType" minOccurs="0"/>
 *         &lt;element name="OverbookedPlaces" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}OverbookedPlacesType" minOccurs="0"/>
 *         &lt;element name="TravelersWithCar" type="{http://www.uic-asso.fr/xml/passenger/02}TravelersWithCarType" minOccurs="0"/>
 *         &lt;element name="AllocatedPlaces" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}AllocatedPlacesType"/>
 *         &lt;element name="BookedOffer" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}BookedOfferType" minOccurs="0"/>
 *         &lt;element name="Meals" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}BookedMealType" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="PositionOfCompartment" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}PositionOfCompartmentType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SeatAllocationType", propOrder = {
    "allocatedTrain",
    "passengers",
    "clazz",
    "coachNumber",
    "coachType",
    "compartmentType",
    "contingent",
    "overbookedPlaces",
    "travelersWithCar",
    "allocatedPlaces",
    "bookedOffer",
    "meals",
    "positionOfCompartment"
})
public class SeatAllocationType {

    @XmlElement(name = "AllocatedTrain", required = true)
    protected AllocatedTrainType allocatedTrain;
    @XmlElement(name = "Passengers")
    @XmlSchemaType(name = "integer")
    protected int passengers;
    @XmlElement(name = "Class", required = true)
    protected String clazz;
    @XmlElement(name = "CoachNumber", required = true)
    protected String coachNumber;
    @XmlElement(name = "CoachType", defaultValue = "0")
    protected Integer coachType;
    @XmlElement(name = "CompartmentType", defaultValue = "0")
    protected Integer compartmentType;
    @XmlElement(name = "Contingent", defaultValue = "0")
    protected Integer contingent;
    @XmlElement(name = "OverbookedPlaces")
    @XmlSchemaType(name = "integer")
    protected Integer overbookedPlaces;
    @XmlElement(name = "TravelersWithCar")
    @XmlSchemaType(name = "integer")
    protected Integer travelersWithCar;
    @XmlElement(name = "AllocatedPlaces", required = true)
    protected AllocatedPlacesType allocatedPlaces;
    @XmlElement(name = "BookedOffer")
    protected BookedOfferType bookedOffer;
    @XmlElement(name = "Meals")
    protected List<BookedMealType> meals;
    @XmlElement(name = "PositionOfCompartment")
    protected BigInteger positionOfCompartment;

    /**
     * Gets the value of the allocatedTrain property.
     * 
     * @return
     *     possible object is
     *     {@link AllocatedTrainType }
     *     
     */
    public AllocatedTrainType getAllocatedTrain() {
        return allocatedTrain;
    }

    /**
     * Sets the value of the allocatedTrain property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllocatedTrainType }
     *     
     */
    public void setAllocatedTrain(AllocatedTrainType value) {
        this.allocatedTrain = value;
    }

    /**
     * Gets the value of the passengers property.
     * 
     */
    public int getPassengers() {
        return passengers;
    }

    /**
     * Sets the value of the passengers property.
     * 
     */
    public void setPassengers(int value) {
        this.passengers = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the coachNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoachNumber() {
        return coachNumber;
    }

    /**
     * Sets the value of the coachNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoachNumber(String value) {
        this.coachNumber = value;
    }

    /**
     * Gets the value of the coachType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCoachType() {
        return coachType;
    }

    /**
     * Sets the value of the coachType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCoachType(Integer value) {
        this.coachType = value;
    }

    /**
     * Gets the value of the compartmentType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCompartmentType() {
        return compartmentType;
    }

    /**
     * Sets the value of the compartmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCompartmentType(Integer value) {
        this.compartmentType = value;
    }

    /**
     * Gets the value of the contingent property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getContingent() {
        return contingent;
    }

    /**
     * Sets the value of the contingent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setContingent(Integer value) {
        this.contingent = value;
    }

    /**
     * Gets the value of the overbookedPlaces property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOverbookedPlaces() {
        return overbookedPlaces;
    }

    /**
     * Sets the value of the overbookedPlaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOverbookedPlaces(Integer value) {
        this.overbookedPlaces = value;
    }

    /**
     * Gets the value of the travelersWithCar property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTravelersWithCar() {
        return travelersWithCar;
    }

    /**
     * Sets the value of the travelersWithCar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTravelersWithCar(Integer value) {
        this.travelersWithCar = value;
    }

    /**
     * Gets the value of the allocatedPlaces property.
     * 
     * @return
     *     possible object is
     *     {@link AllocatedPlacesType }
     *     
     */
    public AllocatedPlacesType getAllocatedPlaces() {
        return allocatedPlaces;
    }

    /**
     * Sets the value of the allocatedPlaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllocatedPlacesType }
     *     
     */
    public void setAllocatedPlaces(AllocatedPlacesType value) {
        this.allocatedPlaces = value;
    }

    /**
     * Gets the value of the bookedOffer property.
     * 
     * @return
     *     possible object is
     *     {@link BookedOfferType }
     *     
     */
    public BookedOfferType getBookedOffer() {
        return bookedOffer;
    }

    /**
     * Sets the value of the bookedOffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookedOfferType }
     *     
     */
    public void setBookedOffer(BookedOfferType value) {
        this.bookedOffer = value;
    }

    /**
     * Gets the value of the meals property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meals property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeals().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BookedMealType }
     * 
     * 
     */
    public List<BookedMealType> getMeals() {
        if (meals == null) {
            meals = new ArrayList<BookedMealType>();
        }
        return this.meals;
    }

    /**
     * Gets the value of the positionOfCompartment property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPositionOfCompartment() {
        return positionOfCompartment;
    }

    /**
     * Sets the value of the positionOfCompartment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPositionOfCompartment(BigInteger value) {
        this.positionOfCompartment = value;
    }

}
