//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import st4rt.convertor.empire.annotation.SupportsRdfId;
import st4rt.convertor.empire.annotation.RdfProperty;
import st4rt.convertor.empire.annotation.SupportsRdfIdImpl;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for StationCodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StationCodeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="CountryCode" type="{http://www.uic-asso.fr/xml/passenger/02}CountryCodeType"/>
 *           &lt;element name="Country" type="{http://www.uic-asso.fr/xml/passenger/02}CountryCodeType"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="LocationPrimaryCode" type="{http://www.uic-asso.fr/xml/passenger/02}StationLocalCodeType"/>
 *           &lt;element name="LocalCode" type="{http://www.uic-asso.fr/xml/passenger/02}StationLocalCodeType"/>
 *         &lt;/choice>
 *         &lt;element name="LocationSubsidiaryCode" type="{http://www.uic-asso.fr/xml/passenger/02}LocationSubsidiaryType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Context" type="{http://www.uic-asso.fr/xml/passenger/02}ContextType" default="UIC" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StationCodeType", namespace = "http://www.uic-asso.fr/xml/passenger/02", propOrder = {
    "countryCode",
    "country",
    "locationPrimaryCode",
    "localCode",
    "locationSubsidiaryCode"
})
@XmlSeeAlso({
    StationCode918Type.class,
    LocationIdent.class
})
public class StationCodeType implements SupportsRdfId {
	
    @XmlTransient
    private SupportsRdfId mIdSupport = new SupportsRdfIdImpl();

    public RdfKey getRdfId() {
        return mIdSupport.getRdfId();
    }

    public void setRdfId(RdfKey theId) {
        mIdSupport.setRdfId(theId);
    }

    @XmlElement(name = "CountryCode", namespace = "http://www.uic-asso.fr/xml/passenger/02")
    protected String countryCode;
    @XmlElement(name = "Country", namespace = "http://www.uic-asso.fr/xml/passenger/02")
    @RdfProperty(propertyName = "st4rt:country")
    protected String country;
    @XmlElement(name = "LocationPrimaryCode", namespace = "http://www.uic-asso.fr/xml/passenger/02")
    @XmlSchemaType(name = "integer")
    protected Integer locationPrimaryCode;
    @XmlElement(name = "LocalCode", namespace = "http://www.uic-asso.fr/xml/passenger/02")
    @XmlSchemaType(name = "integer")
    @RdfProperty(propertyName = "st4rt:station")
    protected Integer localCode;
    @XmlElement(name = "LocationSubsidiaryCode", namespace = "http://www.uic-asso.fr/xml/passenger/02")
    protected LocationSubsidiaryType locationSubsidiaryCode;
    @XmlAttribute(name = "Context")
    protected String context;

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the locationPrimaryCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLocationPrimaryCode() {
        return locationPrimaryCode;
    }

    /**
     * Sets the value of the locationPrimaryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLocationPrimaryCode(Integer value) {
        this.locationPrimaryCode = value;
    }

    /**
     * Gets the value of the localCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLocalCode() {
        return localCode;
    }

    /**
     * Sets the value of the localCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLocalCode(Integer value) {
        this.localCode = value;
    }

    /**
     * Gets the value of the locationSubsidiaryCode property.
     * 
     * @return
     *     possible object is
     *     {@link LocationSubsidiaryType }
     *     
     */
    public LocationSubsidiaryType getLocationSubsidiaryCode() {
        return locationSubsidiaryCode;
    }

    /**
     * Sets the value of the locationSubsidiaryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationSubsidiaryType }
     *     
     */
    public void setLocationSubsidiaryCode(LocationSubsidiaryType value) {
        this.locationSubsidiaryCode = value;
    }

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContext() {
        if (context == null) {
            return "UIC";
        } else {
            return context;
        }
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContext(String value) {
        this.context = value;
    }

}
