//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Requestor" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}RequestorType"/>
 *         &lt;element name="Dialogue" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}DialogueType"/>
 *         &lt;element name="DialogStatus" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}SynchroCodeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestor",
    "dialogue",
    "dialogStatus"
})
@XmlRootElement(name = "SynchroRequest")
public class SynchroRequest {

    @XmlElement(name = "Requestor", required = true)
    protected RequestorType requestor;
    @XmlElement(name = "Dialogue", required = true)
    protected DialogueType dialogue;
    @XmlElement(name = "DialogStatus", required = true)
    protected BigInteger dialogStatus;

    /**
     * Gets the value of the requestor property.
     * 
     * @return
     *     possible object is
     *     {@link RequestorType }
     *     
     */
    public RequestorType getRequestor() {
        return requestor;
    }

    /**
     * Sets the value of the requestor property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestorType }
     *     
     */
    public void setRequestor(RequestorType value) {
        this.requestor = value;
    }

    /**
     * Gets the value of the dialogue property.
     * 
     * @return
     *     possible object is
     *     {@link DialogueType }
     *     
     */
    public DialogueType getDialogue() {
        return dialogue;
    }

    /**
     * Sets the value of the dialogue property.
     * 
     * @param value
     *     allowed object is
     *     {@link DialogueType }
     *     
     */
    public void setDialogue(DialogueType value) {
        this.dialogue = value;
    }

    /**
     * Gets the value of the dialogStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDialogStatus() {
        return dialogStatus;
    }

    /**
     * Sets the value of the dialogStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDialogStatus(BigInteger value) {
        this.dialogStatus = value;
    }

}
