//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Leaflet 918 element  42
 * 
 * <p>Java class for TariffCodeUICType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TariffCodeUICType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.uic-asso.fr/xml/passenger/02}TariffCodeType">
 *       &lt;attribute name="Context" type="{http://www.uic-asso.fr/xml/passenger/02}ContextType" fixed="UIC" />
 *       &lt;attribute name="Code" type="{http://www.uic-asso.fr/xml/passenger/02}TariffCodeCodeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TariffCodeUICType", namespace = "http://www.uic-asso.fr/xml/passenger/02")
public class TariffCodeUICType
    extends TariffCodeType
{


}
