//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import st4rt.convertor.empire.annotation.Queries;
import st4rt.convertor.empire.annotation.Query;
import st4rt.convertor.empire.annotation.SupportsRdfId;
import st4rt.convertor.empire.annotation.Namespaces;
import st4rt.convertor.empire.annotation.RdfProperty;
import st4rt.convertor.empire.annotation.RdfsClass;
import st4rt.convertor.empire.annotation.SupportsRdfIdImpl;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * Data describing the terminal, that issues the request.
 * 
 * <p>Java class for TerminalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TerminalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Number" type="{http://www.uic-asso.fr/xml/passenger/02}TerminalNumberType"/>
 *         &lt;element name="Country" type="{http://www.uic-asso.fr/xml/passenger/02}CountryCodeISO2AType" minOccurs="0"/>
 *         &lt;element name="TravelOfficeOrganization" type="{http://www.uic-asso.fr/xml/passenger/02}TravelOfficeOrganizationType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Type" type="{http://www.uic-asso.fr/xml/passenger/02}TerminalTypeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TerminalType", propOrder = {
    "number",
    "country",
    "travelOfficeOrganization"
})
@Namespaces({
	"st4rt","http://st4rt.eu/ontologies/st4rt#",
	"it2r","http://it2rail.eu/ontology#",
    "foaf","http://xmlns.com/foaf/0.1#",
    "dbp", "http://dbpedia.org/property#",
    "customer", "http://www.it2rail.eu/ontology/customer#"})
@RdfsClass("st4rt:Terminal")
@Queries({
        @Query(name = "918_LW_Default_TerminalType", outputs = {"type"}, type = Query.QueryType.Lowering)
})
public class TerminalType implements SupportsRdfId {

    @XmlTransient
    private SupportsRdfId mIdSupport = new SupportsRdfIdImpl();

    public RdfKey getRdfId() {
        return mIdSupport.getRdfId();
    }

    public void setRdfId(RdfKey theId) {
        mIdSupport.setRdfId(theId);
    }

    @XmlElement(name = "Number", required = true)
    @RdfProperty(propertyName = "st4rt:hasNumber")
    protected String number;
    
    @XmlElement(name = "Country")
    @RdfProperty(propertyName = "st4rt:isInCountry_Alpha2")
    protected String country;
    
    @XmlElement(name = "TravelOfficeOrganization")
    @XmlSchemaType(name = "integer")
    protected Integer travelOfficeOrganization;
    @XmlAttribute(name = "Type")
    protected BigInteger type;

    
    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the travelOfficeOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTravelOfficeOrganization() {
        return travelOfficeOrganization;
    }

    /**
     * Sets the value of the travelOfficeOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTravelOfficeOrganization(Integer value) {
        this.travelOfficeOrganization = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger  getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setType(BigInteger value)  
    {
        this.type = value;
    }

}
