//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TrainStopType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrainStopType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Station" type="{http://www.uic-asso.fr/xml/passenger/02}StationCodeType"/>
 *         &lt;element name="Train">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="TrainNb" use="required" type="{http://www.uic-asso.fr/xml/passenger/02}TrainServiceIdType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Platform" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="Platform" type="{http://www.uic-asso.fr/xml/passenger/02}PlatformType" />
 *                 &lt;attribute name="Track" type="{http://www.uic-asso.fr/xml/passenger/02}TrackType" />
 *                 &lt;attribute name="Section" type="{http://www.uic-asso.fr/xml/passenger/02}PlatformSectionType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Time" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrainStopType", namespace = "http://www.uic-asso.fr/xml/passenger/02", propOrder = {
    "station",
    "train",
    "platform"
})
public class TrainStopType {

    @XmlElement(name = "Station", namespace = "http://www.uic-asso.fr/xml/passenger/02", required = true)
    protected StationCodeType station;
    @XmlElement(name = "Train", namespace = "http://www.uic-asso.fr/xml/passenger/02", required = true)
    protected TrainStopType.Train train;
    @XmlElement(name = "Platform", namespace = "http://www.uic-asso.fr/xml/passenger/02")
    protected TrainStopType.Platform platform;
    @XmlAttribute(name = "Time", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar time;

    /**
     * Gets the value of the station property.
     *
     * @return
     *     possible object is
     *     {@link StationCodeType }
     *
     */
    public StationCodeType getStation() {
        return station;
    }

    /**
     * Sets the value of the station property.
     *
     * @param value
     *     allowed object is
     *     {@link StationCodeType }
     *
     */
    public void setStation(StationCodeType value) {
        this.station = value;
    }

    /**
     * Gets the value of the train property.
     *
     * @return
     *     possible object is
     *     {@link TrainStopType.Train }
     *
     */
    public TrainStopType.Train getTrain() {
        return train;
    }

    /**
     * Sets the value of the train property.
     *
     * @param value
     *     allowed object is
     *     {@link TrainStopType.Train }
     *
     */
    public void setTrain(TrainStopType.Train value) {
        this.train = value;
    }

    /**
     * Gets the value of the platform property.
     *
     * @return
     *     possible object is
     *     {@link TrainStopType.Platform }
     *
     */
    public TrainStopType.Platform getPlatform() {
        return platform;
    }

    /**
     * Sets the value of the platform property.
     *
     * @param value
     *     allowed object is
     *     {@link TrainStopType.Platform }
     *
     */
    public void setPlatform(TrainStopType.Platform value) {
        this.platform = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTime(XMLGregorianCalendar value) {
        this.time = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="Platform" type="{http://www.uic-asso.fr/xml/passenger/02}PlatformType" />
     *       &lt;attribute name="Track" type="{http://www.uic-asso.fr/xml/passenger/02}TrackType" />
     *       &lt;attribute name="Section" type="{http://www.uic-asso.fr/xml/passenger/02}PlatformSectionType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Platform {

        @XmlAttribute(name = "Platform")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String platform;
        @XmlAttribute(name = "Track")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String track;
        @XmlAttribute(name = "Section")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String section;

        /**
         * Gets the value of the platform property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlatform() {
            return platform;
        }

        /**
         * Sets the value of the platform property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlatform(String value) {
            this.platform = value;
        }

        /**
         * Gets the value of the track property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrack() {
            return track;
        }

        /**
         * Sets the value of the track property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrack(String value) {
            this.track = value;
        }

        /**
         * Gets the value of the section property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSection() {
            return section;
        }

        /**
         * Sets the value of the section property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSection(String value) {
            this.section = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="TrainNb" use="required" type="{http://www.uic-asso.fr/xml/passenger/02}TrainServiceIdType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Train {

        @XmlAttribute(name = "TrainNb", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String trainNb;

        /**
         * Gets the value of the trainNb property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrainNb() {
            return trainNb;
        }

        /**
         * Sets the value of the trainNb property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrainNb(String value) {
            this.trainNb = value;
        }

    }

}
