//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Unique identification of a contracted train.  This is not the Train Service Number.
 * 
 * <p>Java class for TrainIdent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrainIdent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PathIdent">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.uic-asso.fr/xml/passenger/02}PathIdent">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ScheduledDepartureDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="PathDepartureLocation" type="{http://www.uic-asso.fr/xml/passenger/02}LocationIdent"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrainIdent", namespace = "http://www.uic-asso.fr/xml/passenger/02", propOrder = {
    "pathIdent",
    "scheduledDepartureDateTime",
    "pathDepartureLocation"
})
public class TrainIdent {

    @XmlElement(name = "PathIdent", namespace = "http://www.uic-asso.fr/xml/passenger/02", required = true)
    protected String pathIdent;
    @XmlElement(name = "ScheduledDepartureDateTime", namespace = "http://www.uic-asso.fr/xml/passenger/02", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar scheduledDepartureDateTime;
    @XmlElement(name = "PathDepartureLocation", namespace = "http://www.uic-asso.fr/xml/passenger/02", required = true)
    protected LocationIdent pathDepartureLocation;

    /**
     * Gets the value of the pathIdent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathIdent() {
        return pathIdent;
    }

    /**
     * Sets the value of the pathIdent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathIdent(String value) {
        this.pathIdent = value;
    }

    /**
     * Gets the value of the scheduledDepartureDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getScheduledDepartureDateTime() {
        return scheduledDepartureDateTime;
    }

    /**
     * Sets the value of the scheduledDepartureDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setScheduledDepartureDateTime(XMLGregorianCalendar value) {
        this.scheduledDepartureDateTime = value;
    }

    /**
     * Gets the value of the pathDepartureLocation property.
     * 
     * @return
     *     possible object is
     *     {@link LocationIdent }
     *     
     */
    public LocationIdent getPathDepartureLocation() {
        return pathDepartureLocation;
    }

    /**
     * Sets the value of the pathDepartureLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationIdent }
     *     
     */
    public void setPathDepartureLocation(LocationIdent value) {
        this.pathDepartureLocation = value;
    }

}
