//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:44:46 AM CEST 
//


package st4rt.convertor.eu.start.standards.TAPTSI918;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * All data concerning the train for car carriage including the information to load and unload a car.
 * 
 * <p>Java class for VehicleLoadingTrainType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehicleLoadingTrainType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DepartureDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="LoadingStationName" type="{http://www.uic-asso.fr/xml/passenger/02}StationNameType"/>
 *         &lt;element name="UnloadingStationName" type="{http://www.uic-asso.fr/xml/passenger/02}StationNameType"/>
 *         &lt;element name="Category" type="{http://www.uic-asso.fr/xml/passenger/02}TrainCategory918Type"/>
 *         &lt;element name="Train" type="{http://www.uic-asso.fr/xml/passenger/02}TrainNumberType"/>
 *         &lt;element name="Loading" type="{http://www.uic-asso.fr/xml/passenger/reservation/01}VehicleLoadingType" maxOccurs="2"/>
 *         &lt;element name="ArrivalDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ServiceBrand" type="{http://www.uic-asso.fr/xml/passenger/02}ServiceBrandInformationType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehicleLoadingTrainType", propOrder = {
    "departureDate",
    "loadingStationName",
    "unloadingStationName",
    "category",
    "train",
    "loading",
    "arrivalDate",
    "serviceBrand"
})
public class VehicleLoadingTrainType {

    @XmlElement(name = "DepartureDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar departureDate;
    @XmlElement(name = "LoadingStationName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String loadingStationName;
    @XmlElement(name = "UnloadingStationName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String unloadingStationName;
    @XmlElement(name = "Category", required = true)
    protected TrainCategory918Type category;
    @XmlElement(name = "Train", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String train;
    @XmlElement(name = "Loading", required = true)
    protected List<VehicleLoadingType> loading;
    @XmlElement(name = "ArrivalDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar arrivalDate;
    @XmlElement(name = "ServiceBrand", required = true)
    protected ServiceBrandInformationType serviceBrand;

    /**
     * Gets the value of the departureDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDepartureDate() {
        return departureDate;
    }

    /**
     * Sets the value of the departureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDepartureDate(XMLGregorianCalendar value) {
        this.departureDate = value;
    }

    /**
     * Gets the value of the loadingStationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoadingStationName() {
        return loadingStationName;
    }

    /**
     * Sets the value of the loadingStationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoadingStationName(String value) {
        this.loadingStationName = value;
    }

    /**
     * Gets the value of the unloadingStationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnloadingStationName() {
        return unloadingStationName;
    }

    /**
     * Sets the value of the unloadingStationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnloadingStationName(String value) {
        this.unloadingStationName = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link TrainCategory918Type }
     *     
     */
    public TrainCategory918Type getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrainCategory918Type }
     *     
     */
    public void setCategory(TrainCategory918Type value) {
        this.category = value;
    }

    /**
     * Gets the value of the train property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrain() {
        return train;
    }

    /**
     * Sets the value of the train property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrain(String value) {
        this.train = value;
    }

    /**
     * Gets the value of the loading property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loading property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoading().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VehicleLoadingType }
     * 
     * 
     */
    public List<VehicleLoadingType> getLoading() {
        if (loading == null) {
            loading = new ArrayList<VehicleLoadingType>();
        }
        return this.loading;
    }

    /**
     * Gets the value of the arrivalDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getArrivalDate() {
        return arrivalDate;
    }

    /**
     * Sets the value of the arrivalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setArrivalDate(XMLGregorianCalendar value) {
        this.arrivalDate = value;
    }

    /**
     * Gets the value of the serviceBrand property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceBrandInformationType }
     *     
     */
    public ServiceBrandInformationType getServiceBrand() {
        return serviceBrand;
    }

    /**
     * Sets the value of the serviceBrand property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceBrandInformationType }
     *     
     */
    public void setServiceBrand(ServiceBrandInformationType value) {
        this.serviceBrand = value;
    }

}
