//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.11 at 11:12:57 AM CET 
//


package eu.st4rt.converter.empire.annotation.xsdgenerated;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Queries_QNAME = new QName("", "queries");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QueriesType }
     * 
     */
    public QueriesType createQueriesType() {
        return new QueriesType();
    }

    /**
     * Create an instance of {@link InputsType }
     * 
     */
    public InputsType createInputsType() {
        return new InputsType();
    }

    /**
     * Create an instance of {@link OutputsType }
     * 
     */
    public OutputsType createOutputsType() {
        return new OutputsType();
    }

    /**
     * Create an instance of {@link QueryType }
     * 
     */
    public QueryType createQueryType() {
        return new QueryType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueriesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "queries")
    public JAXBElement<QueriesType> createQueries(QueriesType value) {
        return new JAXBElement<QueriesType>(_Queries_QNAME, QueriesType.class, null, value);
    }

}
