version: '2.2'

services:
  chimera-example: 
    image: chimera/chimera-example
    build: 
        context: ./
    mem_limit: 1g
    volumes:
      - ./src/main/resources/routes/camel-context.xml:/home/routes/camel-context.xml
      - ./inbox/enrich.ttl:/home/enrich-default.ttl
    networks:
      - chimera-net
  chimera-service: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chimera-example
    ports:
      - 8888:4000
    networks:
      - chimera-net

networks:
  chimera-net:
    driver: bridge


