//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for AfterSalesCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AfterSalesCondition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://domainmodel.pts_fsm.org/2015/10/29/common}FSM.ID">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="UpgradeConstraintId" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" minOccurs="0"/>
 *         &lt;element name="UpgradeIdType" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" minOccurs="0"/>
 *         &lt;element name="Refunding" type="{http://domainmodel.pts_fsm.org/2015/10/29/tariff}Refunding" minOccurs="0"/>
 *         &lt;element name="Exchange" type="{http://domainmodel.pts_fsm.org/2015/10/29/tariff}Exchange" minOccurs="0"/>
 *         &lt;element name="AfterSalesConditionText" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}GenericTextMessage" minOccurs="0"/>
 *         &lt;element name="ImmediatePaymentCondition" type="{http://domainmodel.pts_fsm.org/2015/10/29/payment}ImmediatePaymentCondition" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ImmediatePaymentAvailability" type="{http://domainmodel.pts_fsm.org/2015/10/29/payment}ImmediatePaymentAvailability" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AfterSalesCondition", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/tariff", propOrder = {
    "upgradeConstraintId",
    "upgradeIdType",
    "refunding",
    "exchange",
    "afterSalesConditionText",
    "immediatePaymentCondition"
})
public class AfterSalesCondition
    extends FSMID
{

    @XmlElement(name = "UpgradeConstraintId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String upgradeConstraintId;
    @XmlElement(name = "UpgradeIdType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String upgradeIdType;
    @XmlElement(name = "Refunding")
    protected Refunding refunding;
    @XmlElement(name = "Exchange")
    protected Exchange exchange;
    @XmlElement(name = "AfterSalesConditionText")
    protected GenericTextMessage afterSalesConditionText;
    @XmlElement(name = "ImmediatePaymentCondition")
    protected ImmediatePaymentCondition immediatePaymentCondition;
    @XmlAttribute(name = "ImmediatePaymentAvailability")
    protected ImmediatePaymentAvailability immediatePaymentAvailability;

    /**
     * Gets the value of the upgradeConstraintId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpgradeConstraintId() {
        return upgradeConstraintId;
    }

    /**
     * Sets the value of the upgradeConstraintId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpgradeConstraintId(String value) {
        this.upgradeConstraintId = value;
    }

    /**
     * Gets the value of the upgradeIdType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpgradeIdType() {
        return upgradeIdType;
    }

    /**
     * Sets the value of the upgradeIdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpgradeIdType(String value) {
        this.upgradeIdType = value;
    }

    /**
     * Gets the value of the refunding property.
     * 
     * @return
     *     possible object is
     *     {@link Refunding }
     *     
     */
    public Refunding getRefunding() {
        return refunding;
    }

    /**
     * Sets the value of the refunding property.
     * 
     * @param value
     *     allowed object is
     *     {@link Refunding }
     *     
     */
    public void setRefunding(Refunding value) {
        this.refunding = value;
    }

    /**
     * Gets the value of the exchange property.
     * 
     * @return
     *     possible object is
     *     {@link Exchange }
     *     
     */
    public Exchange getExchange() {
        return exchange;
    }

    /**
     * Sets the value of the exchange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Exchange }
     *     
     */
    public void setExchange(Exchange value) {
        this.exchange = value;
    }

    /**
     * Gets the value of the afterSalesConditionText property.
     * 
     * @return
     *     possible object is
     *     {@link GenericTextMessage }
     *     
     */
    public GenericTextMessage getAfterSalesConditionText() {
        return afterSalesConditionText;
    }

    /**
     * Sets the value of the afterSalesConditionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericTextMessage }
     *     
     */
    public void setAfterSalesConditionText(GenericTextMessage value) {
        this.afterSalesConditionText = value;
    }

    /**
     * Gets the value of the immediatePaymentCondition property.
     * 
     * @return
     *     possible object is
     *     {@link ImmediatePaymentCondition }
     *     
     */
    public ImmediatePaymentCondition getImmediatePaymentCondition() {
        return immediatePaymentCondition;
    }

    /**
     * Sets the value of the immediatePaymentCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImmediatePaymentCondition }
     *     
     */
    public void setImmediatePaymentCondition(ImmediatePaymentCondition value) {
        this.immediatePaymentCondition = value;
    }

    /**
     * Gets the value of the immediatePaymentAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link ImmediatePaymentAvailability }
     *     
     */
    public ImmediatePaymentAvailability getImmediatePaymentAvailability() {
        return immediatePaymentAvailability;
    }

    /**
     * Sets the value of the immediatePaymentAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImmediatePaymentAvailability }
     *     
     */
    public void setImmediatePaymentAvailability(ImmediatePaymentAvailability value) {
        this.immediatePaymentAvailability = value;
    }

}
