//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import st4rt.convertor.empire.annotation.SupportsRdfId;
import st4rt.convertor.empire.annotation.RdfProperty;
import st4rt.convertor.empire.annotation.SupportsRdfIdImpl;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * 
 * 				Both FlatFeeAmount and Percentage can be provided.
 * 			
 * 
 * <p>Java class for Amount complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Amount">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FlatFeeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="PercentageAmount" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}Percentage" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Amount", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/tariff", propOrder = {
    "flatFeeAmount",
    "percentageAmount"
})
public class Amount implements SupportsRdfId {

    @XmlTransient
    private SupportsRdfId mIdSupport = new SupportsRdfIdImpl();

    public RdfKey getRdfId() {
        return mIdSupport.getRdfId();
    }

    public void setRdfId(RdfKey theId) {
        mIdSupport.setRdfId(theId);
    }

    @XmlElement(name = "FlatFeeAmount")
    @RdfProperty(propertyName = "shopping:hasAmount")
    protected BigDecimal flatFeeAmount;
    
    @XmlElement(name = "PercentageAmount")
    protected BigDecimal percentageAmount;

    /**
     * Gets the value of the flatFeeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFlatFeeAmount() {
        return flatFeeAmount;
    }

    /**
     * Sets the value of the flatFeeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFlatFeeAmount(BigDecimal value) {
        this.flatFeeAmount = value;
    }

    /**
     * Gets the value of the percentageAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPercentageAmount() {
        return percentageAmount;
    }

    /**
     * Sets the value of the percentageAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPercentageAmount(BigDecimal value) {
        this.percentageAmount = value;
    }

}
