//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigDecimal;


/**
 * <p>Java class for BoardingPosition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BoardingPosition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://domainmodel.pts_fsm.org/2015/10/29/common}FSM.ID">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="BoardingPositionId" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" />
 *       &lt;attribute name="Height" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="Displacement" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PRMSuitable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="VehicleRampSuitable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BoardingPosition", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/infrastructure")
public class BoardingPosition
    extends FSMID
{

    @XmlAttribute(name = "BoardingPositionId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String boardingPositionId;
    @XmlAttribute(name = "Height")
    protected BigDecimal height;
    @XmlAttribute(name = "Displacement")
    protected String displacement;
    @XmlAttribute(name = "PRMSuitable")
    protected Boolean prmSuitable;
    @XmlAttribute(name = "VehicleRampSuitable")
    protected Boolean vehicleRampSuitable;

    /**
     * Gets the value of the boardingPositionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoardingPositionId() {
        return boardingPositionId;
    }

    /**
     * Sets the value of the boardingPositionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoardingPositionId(String value) {
        this.boardingPositionId = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHeight(BigDecimal value) {
        this.height = value;
    }

    /**
     * Gets the value of the displacement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplacement() {
        return displacement;
    }

    /**
     * Sets the value of the displacement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplacement(String value) {
        this.displacement = value;
    }

    /**
     * Gets the value of the prmSuitable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPRMSuitable() {
        return prmSuitable;
    }

    /**
     * Sets the value of the prmSuitable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPRMSuitable(Boolean value) {
        this.prmSuitable = value;
    }

    /**
     * Gets the value of the vehicleRampSuitable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVehicleRampSuitable() {
        return vehicleRampSuitable;
    }

    /**
     * Sets the value of the vehicleRampSuitable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVehicleRampSuitable(Boolean value) {
        this.vehicleRampSuitable = value;
    }

}
