//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import st4rt.convertor.empire.annotation.Link;
import st4rt.convertor.empire.annotation.Query;
import st4rt.convertor.empire.annotation.RdfProperty;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 *
 *
 * 				 A business entity created by the Booking process constituting the digital, persistent record of the business agreement established between
 * 							a Retailer/ Commercial Distributor and a Rail Service Provider by a Booking transaction, where the Rail Service Provider commits to supply 
 * 							the Products described in the booked Carrier Offer(s) and the Retailer/ Commercial Distributor commits to reward the Rail Service Provider 
 * 							for the supplied Products according to the terms and conditions associated with the Carrier Offer(s).
 * 				 Note: Booking is the basis for establishing the relationship (i.e. Contract of Carriage) between Customer/ Passenger and Carrier through 
 * 							the fulfilment and payment process. 
 *
 *
 *
 * <p>Java class for Booking complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Booking">
 *   &lt;complexContent>
 *     &lt;extension base="{http://domainmodel.pts_fsm.org/2015/10/29/common}FSM.ID">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="BookingCommercialRef" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" minOccurs="0"/>
 *         &lt;element name="RelatedBookingIdRefsList" type="{http://www.w3.org/2001/XMLSchema}NMTOKENS" minOccurs="0"/>
 *         &lt;element name="BookingTimeLimit" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="CarrierServiceItem" type="{http://domainmodel.pts_fsm.org/2015/10/29/booking}CarrierServiceItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Itinerary" type="{http://domainmodel.pts_fsm.org/2015/10/29/journeyplan}Itinerary" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Passenger" type="{http://domainmodel.pts_fsm.org/2015/10/29/passenger}PassengerData" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ContactInformation" type="{http://domainmodel.pts_fsm.org/2015/10/29/passenger}ContactInformation" minOccurs="0"/>
 *         &lt;element name="BookingStatus" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}GenericStatus" minOccurs="0"/>
 *         &lt;element name="PaymentMode" type="{http://domainmodel.pts_fsm.org/2015/10/29/payment}PaymentMode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FulfilmentMethod" type="{http://domainmodel.pts_fsm.org/2015/10/29/fulfilment}FulfilmentMethod" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Remark" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}GenericTextMessage" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Booking", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/booking", propOrder = {
        "bookingCommercialRef",
        "relatedBookingIdRefsList",
        "bookingTimeLimit",
        "carrierServiceItem",
        "itinerary",
        "passenger",
        "contactInformation",
        "bookingStatus",
        "paymentMode",
        "fulfilmentMethod",
        "remark"
})
public class Booking
        extends FSMID
{

    @XmlElement(name = "BookingCommercialRef")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    @RdfProperty(links = {
            @Link(propertyName = "travel:hasItineraryOffer", nodeType = Link.NodeType.Shared, sharedID = "IDforItineraryOffer"),
            @Link(propertyName = "mobility:hasBookedItineraryOffer", nodeType = Link.NodeType.Shared, sharedID = "IDforBookedItineraryOffer")},
            propertyName = "mobility:hasReference")
    @Query(name = "FSM_LW_BookingCommercialRef", type = Query.QueryType.Lowering, outputs = {"bookingCommercialRef"})
    protected String bookingCommercialRef;
    @XmlList
    @XmlElement(name = "RelatedBookingIdRefsList")
    @XmlSchemaType(name = "NMTOKENS")
    protected List<String> relatedBookingIdRefsList;
    @XmlElement(name = "BookingTimeLimit")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar bookingTimeLimit;
    @XmlElement(name = "CarrierServiceItem")
    protected List<CarrierServiceItem> carrierServiceItem;
    @XmlElement(name = "Itinerary")
    @RdfProperty(links = {
            @Link(propertyName = "travel:hasItineraryOffer", nodeType = Link.NodeType.Shared, sharedID = "IDforItineraryOffer")},
            propertyName = "st4rt:hasItinerary")
    protected List<Itinerary> itinerary;
    @XmlElement(name = "Passenger")

    @RdfProperty(links = {
            @Link(propertyName = "travel:hasItineraryOffer", nodeType = Link.NodeType.Shared, sharedID = "IDforItineraryOffer")},
            propertyName = "travel:hasCustomer")
    protected List<PassengerData> passenger;

    @XmlElement(name = "ContactInformation")
    protected ContactInformation contactInformation;
    @XmlElement(name = "BookingStatus")
    protected GenericStatus bookingStatus;
    @XmlElement(name = "PaymentMode")
    protected List<PaymentMode> paymentMode;
    @XmlElement(name = "FulfilmentMethod")
    protected List<FulfilmentMethod> fulfilmentMethod;
    @XmlElement(name = "Remark")
    protected GenericTextMessage remark;

    /**
     * Gets the value of the bookingCommercialRef property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBookingCommercialRef() {
        return bookingCommercialRef;
    }

    /**
     * Sets the value of the bookingCommercialRef property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBookingCommercialRef(String value) {
        this.bookingCommercialRef = value;
    }

    /**
     * Gets the value of the relatedBookingIdRefsList property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedBookingIdRefsList property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedBookingIdRefsList().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getRelatedBookingIdRefsList() {
        if (relatedBookingIdRefsList == null) {
            relatedBookingIdRefsList = new ArrayList<String>();
        }
        return this.relatedBookingIdRefsList;
    }

    /**
     * Gets the value of the bookingTimeLimit property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getBookingTimeLimit() {
        return bookingTimeLimit;
    }

    /**
     * Sets the value of the bookingTimeLimit property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setBookingTimeLimit(XMLGregorianCalendar value) {
        this.bookingTimeLimit = value;
    }

    /**
     * Gets the value of the carrierServiceItem property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the carrierServiceItem property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCarrierServiceItem().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CarrierServiceItem }
     *
     *
     */
    public List<CarrierServiceItem> getCarrierServiceItem() {
        if (carrierServiceItem == null) {
            carrierServiceItem = new ArrayList<CarrierServiceItem>();
        }
        return this.carrierServiceItem;
    }

    /**
     * Gets the value of the itinerary property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itinerary property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItinerary().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Itinerary }
     *
     *
     */
    public List<Itinerary> getItinerary() {
        if (itinerary == null) {
            itinerary = new ArrayList<Itinerary>();
        }
        return this.itinerary;
    }

    /**
     * Gets the value of the passenger property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the passenger property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPassenger().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PassengerData }
     *
     *
     */
    public List<PassengerData> getPassenger() {
        if (passenger == null) {
            passenger = new ArrayList<PassengerData>();
        }
        return this.passenger;
    }

    /**
     * Gets the value of the contactInformation property.
     *
     * @return
     *     possible object is
     *     {@link ContactInformation }
     *
     */
    public ContactInformation getContactInformation() {
        return contactInformation;
    }

    /**
     * Sets the value of the contactInformation property.
     *
     * @param value
     *     allowed object is
     *     {@link ContactInformation }
     *
     */
    public void setContactInformation(ContactInformation value) {
        this.contactInformation = value;
    }

    /**
     * Gets the value of the bookingStatus property.
     *
     * @return
     *     possible object is
     *     {@link GenericStatus }
     *
     */
    public GenericStatus getBookingStatus() {
        return bookingStatus;
    }

    /**
     * Sets the value of the bookingStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link GenericStatus }
     *
     */
    public void setBookingStatus(GenericStatus value) {
        this.bookingStatus = value;
    }

    /**
     * Gets the value of the paymentMode property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentMode property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentMode().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentMode }
     *
     *
     */
    public List<PaymentMode> getPaymentMode() {
        if (paymentMode == null) {
            paymentMode = new ArrayList<PaymentMode>();
        }
        return this.paymentMode;
    }

    /**
     * Gets the value of the fulfilmentMethod property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fulfilmentMethod property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFulfilmentMethod().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FulfilmentMethod }
     *
     *
     */
    public List<FulfilmentMethod> getFulfilmentMethod() {
        if (fulfilmentMethod == null) {
            fulfilmentMethod = new ArrayList<FulfilmentMethod>();
        }
        return this.fulfilmentMethod;
    }

    /**
     * Gets the value of the remark property.
     *
     * @return
     *     possible object is
     *     {@link GenericTextMessage }
     *
     */
    public GenericTextMessage getRemark() {
        return remark;
    }

    /**
     * Sets the value of the remark property.
     *
     * @param value
     *     allowed object is
     *     {@link GenericTextMessage }
     *
     */
    public void setRemark(GenericTextMessage value) {
        this.remark = value;
    }

}
