//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigDecimal;


/**
 * <p>Java class for CarbonFootPrint complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CarbonFootPrint">
 *   &lt;complexContent>
 *     &lt;extension base="{http://domainmodel.pts_fsm.org/2015/10/29/common}FSM.ID">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="co2Unit" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID"/>
 *         &lt;element name="co2Emission" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}NumericNonNegativeDecimal"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CarbonFootPrint", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/journeyplan", propOrder = {
    "co2Unit",
    "co2Emission"
})
public class CarbonFootPrint
    extends FSMID
{

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String co2Unit;
    protected BigDecimal co2Emission;

    /**
     * Gets the value of the co2Unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCo2Unit() {
        return co2Unit;
    }

    /**
     * Sets the value of the co2Unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCo2Unit(String value) {
        this.co2Unit = value;
    }

    /**
     * Gets the value of the co2Emission property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCo2Emission() {
        return co2Emission;
    }

    /**
     * Sets the value of the co2Emission property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCo2Emission(BigDecimal value) {
        this.co2Emission = value;
    }

}
