//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ConfirmedAncillaryService complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConfirmedAncillaryService">
 *   &lt;complexContent>
 *     &lt;extension base="{http://domainmodel.pts_fsm.org/2015/10/29/offering}RequestedAncillaryService">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="PassengerRefsList" type="{http://www.w3.org/2001/XMLSchema}IDREFS"/>
 *         &lt;element name="AvailabilityConstraintId" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StopPlace" type="{http://domainmodel.pts_fsm.org/2015/10/29/infrastructure}StopPlace" minOccurs="0"/>
 *         &lt;element name="Fare" type="{http://domainmodel.pts_fsm.org/2015/10/29/tariff}Fare" minOccurs="0"/>
 *         &lt;element name="SalesCondition" type="{http://domainmodel.pts_fsm.org/2015/10/29/tariff}SalesCondition" minOccurs="0"/>
 *         &lt;element name="AfterSalesCondition" type="{http://domainmodel.pts_fsm.org/2015/10/29/tariff}AfterSalesCondition" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Reservable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfirmedAncillaryService", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/offering", propOrder = {
    "passengerRefsList",
    "availabilityConstraintId",
    "stopPlace",
    "fare",
    "salesCondition",
    "afterSalesCondition"
})
public class ConfirmedAncillaryService
    extends RequestedAncillaryService
{

    @XmlList
    @XmlElement(name = "PassengerRefsList")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> passengerRefsList;
    @XmlElement(name = "AvailabilityConstraintId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected List<String> availabilityConstraintId;
    @XmlElement(name = "StopPlace")
    protected StopPlace stopPlace;
    @XmlElement(name = "Fare")
    protected Fare fare;
    @XmlElement(name = "SalesCondition")
    protected SalesCondition salesCondition;
    @XmlElementRef(name = "AfterSalesCondition", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/offering", type = JAXBElement.class, required = false)
    protected JAXBElement<AfterSalesCondition> afterSalesCondition;
    @XmlAttribute(name = "Reservable")
    protected Boolean reservable;

    /**
     * Gets the value of the passengerRefsList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the passengerRefsList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPassengerRefsList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getPassengerRefsList() {
        if (passengerRefsList == null) {
            passengerRefsList = new ArrayList<Object>();
        }
        return this.passengerRefsList;
    }

    /**
     * Gets the value of the availabilityConstraintId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the availabilityConstraintId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAvailabilityConstraintId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAvailabilityConstraintId() {
        if (availabilityConstraintId == null) {
            availabilityConstraintId = new ArrayList<String>();
        }
        return this.availabilityConstraintId;
    }

    /**
     * Gets the value of the stopPlace property.
     * 
     * @return
     *     possible object is
     *     {@link StopPlace }
     *     
     */
    public StopPlace getStopPlace() {
        return stopPlace;
    }

    /**
     * Sets the value of the stopPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopPlace }
     *     
     */
    public void setStopPlace(StopPlace value) {
        this.stopPlace = value;
    }

    /**
     * Gets the value of the fare property.
     * 
     * @return
     *     possible object is
     *     {@link Fare }
     *     
     */
    public Fare getFare() {
        return fare;
    }

    /**
     * Sets the value of the fare property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fare }
     *     
     */
    public void setFare(Fare value) {
        this.fare = value;
    }

    /**
     * Gets the value of the salesCondition property.
     * 
     * @return
     *     possible object is
     *     {@link SalesCondition }
     *     
     */
    public SalesCondition getSalesCondition() {
        return salesCondition;
    }

    /**
     * Sets the value of the salesCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesCondition }
     *     
     */
    public void setSalesCondition(SalesCondition value) {
        this.salesCondition = value;
    }

    /**
     * Gets the value of the afterSalesCondition property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AfterSalesCondition }{@code >}
     *     
     */
    public JAXBElement<AfterSalesCondition> getAfterSalesCondition() {
        return afterSalesCondition;
    }

    /**
     * Sets the value of the afterSalesCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AfterSalesCondition }{@code >}
     *     
     */
    public void setAfterSalesCondition(JAXBElement<AfterSalesCondition> value) {
        this.afterSalesCondition = value;
    }

    /**
     * Gets the value of the reservable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReservable() {
        return reservable;
    }

    /**
     * Sets the value of the reservable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReservable(Boolean value) {
        this.reservable = value;
    }

}
