//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import st4rt.convertor.empire.annotation.Queries;
import st4rt.convertor.empire.annotation.Query;
import st4rt.convertor.empire.annotation.Query.QueryType;
import st4rt.convertor.empire.annotation.NamedGraph;
import st4rt.convertor.empire.annotation.Namespaces;
import st4rt.convertor.empire.annotation.RdfProperty;
import st4rt.convertor.empire.annotation.RdfsClass;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>Java class for ContactInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContactInformation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://domainmodel.pts_fsm.org/2015/10/29/common}FSM.ID">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Gender" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" minOccurs="0"/>
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Address1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Address2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Address3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Address4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ZipCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MobilePhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LandlinePhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DeclineRecontact" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="MandatoryRecontact" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContactInformation", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/passenger", propOrder = {
    "gender",
    "lastName",
    "firstName",
    "address1",
    "address2",
    "address3",
    "address4",
    "city",
    "zipCode",
    "country",
    "mobilePhoneNumber",
    "landlinePhoneNumber",
    "emailAddress",
    "declineRecontact",
    "mandatoryRecontact"
})

@NamedGraph(type = NamedGraph.NamedGraphType.Static,
value = "http://st4rt.eu/ontologies/st4rt/message")
@Namespaces({
	"http://st4rt.eu/ontologies/st4rt#",
	"it2r","http://it2rail.eu/ontology#",
    "foaf","http://xmlns.com/foaf/0.1#",
    "dbp", "http://dbpedia.org/property#",
    "customer", "http://www.it2rail.eu/ontology/customer#"})
@RdfsClass("customer:Passenger")
@Queries({
	@Query(name = "FSM_LF_ContactInformation", inputs = {"country"}),
	@Query(name = "FSM_LW_ContactInformation", outputs = {"gender", "country"}, type = QueryType.Lowering)})
public class ContactInformation
    extends FSMID
{

    @XmlElement(name = "Gender")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    @RdfProperty(propertyName = "foaf:gender")
    protected String gender;
    
    
    @XmlElement(name = "LastName")
    @RdfProperty(propertyName = "foaf:family_name")
    protected String lastName;
    
    @XmlElement(name = "FirstName")
    @RdfProperty(propertyName = "foaf:name")
    protected String firstName;
    
    @XmlElement(name = "Address1")
    @RdfProperty(propertyName = "st4rt:address1")
    protected String address1;
    
    @XmlElement(name = "Address2")
    @RdfProperty(propertyName = "st4rt:address2")
    protected String address2;
    
    @XmlElement(name = "Address3")
    @RdfProperty(propertyName = "st4rt:address3")
    protected String address3;
    
    @XmlElement(name = "Address4")
    @RdfProperty(propertyName = "st4rt:address4")
    protected String address4;
    
    @RdfProperty(propertyName = "infrastructure:isInCity")
    @XmlElement(name = "City")
    protected String city;
    
    @RdfProperty(propertyName = "dbp:zipcode")
    @XmlElement(name = "ZipCode")
    protected String zipCode;

    @XmlElement(name = "Country")
    protected String country;
    
    @RdfProperty(propertyName = "st4rt:mobilePhoneNumber")
    @XmlElement(name = "MobilePhoneNumber")
    protected String mobilePhoneNumber;
    
    @RdfProperty(propertyName = "st4rt:landLinePhoneNumber")
    @XmlElement(name = "LandlinePhoneNumber")
    protected List<String> landlinePhoneNumber;
    
    @RdfProperty(propertyName = "foaf:mbox")
    @XmlElement(name = "EmailAddress")
    protected String emailAddress;
    
    @RdfProperty(propertyName = "st4rt:declineRecontact")
    @XmlElement(name = "DeclineRecontact")
    protected Boolean declineRecontact;
    
    @RdfProperty(propertyName = "st4rt:mandatoryRecontact")
    @XmlElement(name = "MandatoryRecontact")
    protected Boolean mandatoryRecontact;

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
//    @RdfProperty("foaf:gender")
//    public void setGender(@Sparql(name = "setGender", inputs = {}) String value) {
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the address1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * Sets the value of the address1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress1(String value) {
        this.address1 = value;
    }

    /**
     * Gets the value of the address2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * Sets the value of the address2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress2(String value) {
        this.address2 = value;
    }

    /**
     * Gets the value of the address3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress3() {
        return address3;
    }

    /**
     * Sets the value of the address3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress3(String value) {
        this.address3 = value;
    }

    /**
     * Gets the value of the address4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress4() {
        return address4;
    }

    /**
     * Sets the value of the address4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress4(String value) {
        this.address4 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the zipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * Sets the value of the zipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipCode(String value) {
        this.zipCode = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
//    @RdfProperty("st4rt:isInCountry_Alpha2")
//    public void setCountry(@Sparql(name = "setCountry", inputs = {}) String value) {
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the mobilePhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobilePhoneNumber() {
        return mobilePhoneNumber;
    }

    /**
     * Sets the value of the mobilePhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobilePhoneNumber(String value) {
        this.mobilePhoneNumber = value;
    }

    /**
     * Gets the value of the landlinePhoneNumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the landlinePhoneNumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLandlinePhoneNumber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLandlinePhoneNumber() {
        if (landlinePhoneNumber == null) {
            landlinePhoneNumber = new ArrayList<String>();
        }
        return this.landlinePhoneNumber;
    }

    /**
     * Gets the value of the emailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress(String value) {
        this.emailAddress = value;
    }

    /**
     * Gets the value of the declineRecontact property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeclineRecontact() {
        return declineRecontact;
    }

    /**
     * Sets the value of the declineRecontact property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeclineRecontact(Boolean value) {
        this.declineRecontact = value;
    }

    /**
     * Gets the value of the mandatoryRecontact property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMandatoryRecontact() {
        return mandatoryRecontact;
    }

    /**
     * Sets the value of the mandatoryRecontact property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMandatoryRecontact(Boolean value) {
        this.mandatoryRecontact = value;
    }

}
