//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Indicates weather additional information is required for identification during the sale process.
 * 
 * <p>Java class for ControllingConstraint complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ControllingConstraint">
 *   &lt;complexContent>
 *     &lt;extension base="{http://domainmodel.pts_fsm.org/2015/10/29/common}FSM.ID">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="ProofOfIdentityId" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID"/>
 *         &lt;element name="CardIssuerId" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID"/>
 *       &lt;/sequence>
 *       &lt;attribute name="IdentityByAccount" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="AccountDirectoryOwner" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ControllingConstraint", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/tariff", propOrder = {
    "proofOfIdentityId",
    "cardIssuerId"
})
public class ControllingConstraint
    extends FSMID
{

    @XmlElement(name = "ProofOfIdentityId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String proofOfIdentityId;
    @XmlElement(name = "CardIssuerId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String cardIssuerId;
    @XmlAttribute(name = "IdentityByAccount")
    protected String identityByAccount;
    @XmlAttribute(name = "AccountDirectoryOwner")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String accountDirectoryOwner;

    /**
     * Gets the value of the proofOfIdentityId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProofOfIdentityId() {
        return proofOfIdentityId;
    }

    /**
     * Sets the value of the proofOfIdentityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProofOfIdentityId(String value) {
        this.proofOfIdentityId = value;
    }

    /**
     * Gets the value of the cardIssuerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardIssuerId() {
        return cardIssuerId;
    }

    /**
     * Sets the value of the cardIssuerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardIssuerId(String value) {
        this.cardIssuerId = value;
    }

    /**
     * Gets the value of the identityByAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentityByAccount() {
        return identityByAccount;
    }

    /**
     * Sets the value of the identityByAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentityByAccount(String value) {
        this.identityByAccount = value;
    }

    /**
     * Gets the value of the accountDirectoryOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountDirectoryOwner() {
        return accountDirectoryOwner;
    }

    /**
     * Sets the value of the accountDirectoryOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountDirectoryOwner(String value) {
        this.accountDirectoryOwner = value;
    }

}
