//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import st4rt.convertor.empire.annotation.NamedGraph;
import st4rt.convertor.empire.annotation.Namespaces;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for DirectBookingParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DirectBookingParameters">
 *   &lt;complexContent>
 *     &lt;extension base="{http://domainmodel.pts_fsm.org/2015/10/29/offering}OfferParameters">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="DirectBookingProductId" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" minOccurs="0"/>
 *         &lt;element name="SalesChannelTypeId" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DirectBookingParameters", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/offering", propOrder = {
    "directBookingProductId",
    "salesChannelTypeId"
})

@NamedGraph(type = NamedGraph.NamedGraphType.Static)
@Namespaces({
	"st4rt","http://st4rt.eu/ontologies/st4rt#",
	"it2r","http://it2rail.eu/ontology#",
    "foaf","http://xmlns.com/foaf/0.1#",
    "dbp", "http://dbpedia.org/property#"})
public class DirectBookingParameters
    extends OfferParameters
{

    @XmlElement(name = "DirectBookingProductId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String directBookingProductId;
    
    @XmlElement(name = "SalesChannelTypeId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String salesChannelTypeId;

    /**
     * Gets the value of the directBookingProductId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectBookingProductId() {
        return directBookingProductId;
    }

    /**
     * Sets the value of the directBookingProductId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectBookingProductId(String value) {
        this.directBookingProductId = value;
    }

    /**
     * Gets the value of the salesChannelTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesChannelTypeId() {
        return salesChannelTypeId;
    }

    /**
     * Sets the value of the salesChannelTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesChannelTypeId(String value) {
        this.salesChannelTypeId = value;
    }

}
