//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for EndpointReference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EndpointReference">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="From" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="To" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Action" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ReplyTo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FaultTo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MessageId" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" />
 *       &lt;attribute name="ServiceLevel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Security" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ServiceReplyVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EndpointReference")
public class EndpointReference {

    @XmlAttribute(name = "From")
    protected String from;
    @XmlAttribute(name = "To")
    protected String to;
    @XmlAttribute(name = "Action")
    protected String action;
    @XmlAttribute(name = "ReplyTo")
    protected String replyTo;
    @XmlAttribute(name = "FaultTo")
    protected String faultTo;
    @XmlAttribute(name = "MessageId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String messageId;
    @XmlAttribute(name = "ServiceLevel")
    protected String serviceLevel;
    @XmlAttribute(name = "Security")
    protected String security;
    @XmlAttribute(name = "ServiceRequestVersion")
    protected String serviceRequestVersion;
    @XmlAttribute(name = "ServiceReplyVersion")
    protected String serviceReplyVersion;

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrom(String value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTo(String value) {
        this.to = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the replyTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplyTo() {
        return replyTo;
    }

    /**
     * Sets the value of the replyTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplyTo(String value) {
        this.replyTo = value;
    }

    /**
     * Gets the value of the faultTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaultTo() {
        return faultTo;
    }

    /**
     * Sets the value of the faultTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaultTo(String value) {
        this.faultTo = value;
    }

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageId(String value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the serviceLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceLevel() {
        return serviceLevel;
    }

    /**
     * Sets the value of the serviceLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceLevel(String value) {
        this.serviceLevel = value;
    }

    /**
     * Gets the value of the security property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurity(String value) {
        this.security = value;
    }

    /**
     * Gets the value of the serviceRequestVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceRequestVersion() {
        return serviceRequestVersion;
    }

    /**
     * Sets the value of the serviceRequestVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceRequestVersion(String value) {
        this.serviceRequestVersion = value;
    }

    /**
     * Gets the value of the serviceReplyVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceReplyVersion() {
        return serviceReplyVersion;
    }

    /**
     * Sets the value of the serviceReplyVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceReplyVersion(String value) {
        this.serviceReplyVersion = value;
    }

}
