//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * The Endpoint of a technical address consists of name of interface, a final address, the type of binding to this address and a path (URI) to get the contract (wsdl). The final address is defined according to WS Addressing.
 * 			
 * 
 * <p>Java class for Endpoint complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Endpoint">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="AuthenticationModeId" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" minOccurs="0"/>
 *         &lt;element name="Binding" type="{http://servicemodel.pts_fsm.org/2015/10/29/fsm.common.headers}Binding" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EndpointBehavior" type="{http://servicemodel.pts_fsm.org/2015/10/29/fsm.common.headers}EndpointBehavior" minOccurs="0"/>
 *         &lt;element name="EndpointReference" type="{http://servicemodel.pts_fsm.org/2015/10/29/fsm.common.headers}EndpointReference" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Contract" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ContractVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Endpoint", propOrder = {
    "authenticationModeId",
    "binding",
    "endpointBehavior",
    "endpointReference"
})
public class Endpoint {

    @XmlElement(name = "AuthenticationModeId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String authenticationModeId;
    @XmlElement(name = "Binding")
    protected List<Binding> binding;
    @XmlElement(name = "EndpointBehavior")
    protected EndpointBehavior endpointBehavior;
    @XmlElement(name = "EndpointReference")
    protected EndpointReference endpointReference;
    @XmlAttribute(name = "Name")
    protected String name;
    @XmlAttribute(name = "Contract")
    protected String contract;
    @XmlAttribute(name = "ContractVersion")
    protected String contractVersion;

    /**
     * Gets the value of the authenticationModeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthenticationModeId() {
        return authenticationModeId;
    }

    /**
     * Sets the value of the authenticationModeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthenticationModeId(String value) {
        this.authenticationModeId = value;
    }

    /**
     * Gets the value of the binding property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the binding property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBinding().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Binding }
     * 
     * 
     */
    public List<Binding> getBinding() {
        if (binding == null) {
            binding = new ArrayList<Binding>();
        }
        return this.binding;
    }

    /**
     * Gets the value of the endpointBehavior property.
     * 
     * @return
     *     possible object is
     *     {@link EndpointBehavior }
     *     
     */
    public EndpointBehavior getEndpointBehavior() {
        return endpointBehavior;
    }

    /**
     * Sets the value of the endpointBehavior property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndpointBehavior }
     *     
     */
    public void setEndpointBehavior(EndpointBehavior value) {
        this.endpointBehavior = value;
    }

    /**
     * Gets the value of the endpointReference property.
     * 
     * @return
     *     possible object is
     *     {@link EndpointReference }
     *     
     */
    public EndpointReference getEndpointReference() {
        return endpointReference;
    }

    /**
     * Sets the value of the endpointReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndpointReference }
     *     
     */
    public void setEndpointReference(EndpointReference value) {
        this.endpointReference = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the contract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContract() {
        return contract;
    }

    /**
     * Sets the value of the contract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContract(String value) {
        this.contract = value;
    }

    /**
     * Gets the value of the contractVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractVersion() {
        return contractVersion;
    }

    /**
     * Sets the value of the contractVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractVersion(String value) {
        this.contractVersion = value;
    }

}
