//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import st4rt.convertor.empire.annotation.SupportsRdfId;
import st4rt.convertor.empire.annotation.Query;
import st4rt.convertor.empire.annotation.RdfProperty;
import st4rt.convertor.empire.annotation.RdfsClass;
import st4rt.convertor.empire.annotation.SupportsRdfIdImpl;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Fare complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Fare">
 *   &lt;complexContent>
 *     &lt;extension base="{http://domainmodel.pts_fsm.org/2015/10/29/common}FSM.ID">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="RSPPrice" type="{http://domainmodel.pts_fsm.org/2015/10/29/tariff}RSPPrice"/>
 *         &lt;element name="NetPrice" type="{http://domainmodel.pts_fsm.org/2015/10/29/tariff}NetPrice" minOccurs="0"/>
 *         &lt;element name="Discount" type="{http://domainmodel.pts_fsm.org/2015/10/29/tariff}Discount" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="VAT" type="{http://domainmodel.pts_fsm.org/2015/10/29/tariff}VAT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Charge" type="{http://domainmodel.pts_fsm.org/2015/10/29/tariff}Charge" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="FareTypeId" use="required" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Fare", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/tariff", propOrder = {
    "rspPrice",
    "netPrice",
    "discount",
    "vat",
    "charge"
})
@XmlSeeAlso({
    AfterSaleFare.class
})
@RdfsClass("shopping:GlobalQuotation")
public class Fare
    extends FSMID implements SupportsRdfId {

    @XmlTransient
    private SupportsRdfId mIdSupport = new SupportsRdfIdImpl();

    public RdfKey getRdfId() {
        return mIdSupport.getRdfId();
    }

    public void setRdfId(RdfKey theId) {
        mIdSupport.setRdfId(theId);
    }

    @XmlElement(name = "RSPPrice")
    @RdfProperty(propertyName = "shopping:hasPrice")
    protected RSPPrice rspPrice;

    @XmlElement(name = "NetPrice")
    protected NetPrice netPrice;
    @XmlElement(name = "Discount")
    protected List<Discount> discount;
    @XmlElement(name = "VAT")
    protected List<VAT> vat;
    @XmlElement(name = "Charge")
    protected List<Charge> charge;
    @XmlAttribute(name = "FareTypeId", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @Query(name = "FSM_LW_FareType", type = Query.QueryType.Lowering, outputs = {"fareTypeId"})
    protected String fareTypeId;

    /**
     * Gets the value of the rspPrice property.
     * 
     * @return
     *     possible object is
     *     {@link RSPPrice }
     *     
     */
    public RSPPrice getRspPrice() {
        return rspPrice;
    }

    /**
     * Sets the value of the rspPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link RSPPrice }
     *     
     */
    public void setRspPrice(RSPPrice value) {
        this.rspPrice = value;
    }

    /**
     * Gets the value of the netPrice property.
     * 
     * @return
     *     possible object is
     *     {@link NetPrice }
     *     
     */
    public NetPrice getNetPrice() {
        return netPrice;
    }

    /**
     * Sets the value of the netPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetPrice }
     *     
     */
    public void setNetPrice(NetPrice value) {
        this.netPrice = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the discount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiscount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Discount }
     * 
     * 
     */
    public List<Discount> getDiscount() {
        if (discount == null) {
            discount = new ArrayList<Discount>();
        }
        return this.discount;
    }

    /**
     * Gets the value of the vat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVAT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VAT }
     * 
     * 
     */
    public List<VAT> getVat() {
        if (vat == null) {
            vat = new ArrayList<VAT>();
        }
        return this.vat;
    }

    /**
     * Gets the value of the charge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the charge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCharge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Charge }
     * 
     * 
     */
    public List<Charge> getCharge() {
        if (charge == null) {
            charge = new ArrayList<Charge>();
        }
        return this.charge;
    }

    /**
     * Gets the value of the fareTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFareTypeId() {
        return fareTypeId;
    }

    /**
     * Sets the value of the fareTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFareTypeId(String value) {
        this.fareTypeId = value;
    }

}
