//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Fault complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Fault">
 *   &lt;complexContent>
 *     &lt;extension base="{http://servicemodel.pts_fsm.org/2015/10/29/fsm.notification.messages}Notification">
 *       &lt;sequence>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Fault", namespace = "http://servicemodel.pts_fsm.org/2015/10/29/fsm.notification.messages")
@XmlSeeAlso({
    PreRefundFault.class,
    ImmediatePaymentFault.class,
    ConfirmRefundFault.class,
    ExchangeConfirmBookingFault.class,
    FulfilmentFault.class,
    OfferRequestFault.class,
    PreBookingFault.class,
    RevokeBookingFault.class,
    ExchangePreBookingFault.class,
    ConfirmBookingFault.class,
    RevokeRefundRequest.class,
    InitiateRefundFault.class,
    RetrieveBookingFault.class,
    FulfilmentNotificationFault.class,
    UpdateInformationFault.class,
    ExchangeOfferFault.class,
    ExchangeRevokeFault.class,
    ServiceLevelFault.class,
    SecurityFault.class,
    ProtocolFault.class
})
public class Fault
    extends Notification
{


}
