//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 			
 * 
 * <p>Java class for FilterCriteria complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FilterCriteria">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FilterCriteriaType" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID"/>
 *         &lt;element name="FilterCriteriaId" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FilterCriteria", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/offering", propOrder = {
    "filterCriteriaType",
    "filterCriteriaId"
})
public class FilterCriteria {

    @XmlElement(name = "FilterCriteriaType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String filterCriteriaType;
    @XmlElement(name = "FilterCriteriaId", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String filterCriteriaId;

    /**
     * Gets the value of the filterCriteriaType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilterCriteriaType() {
        return filterCriteriaType;
    }

    /**
     * Sets the value of the filterCriteriaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilterCriteriaType(String value) {
        this.filterCriteriaType = value;
    }

    /**
     * Gets the value of the filterCriteriaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilterCriteriaId() {
        return filterCriteriaId;
    }

    /**
     * Sets the value of the filterCriteriaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilterCriteriaId(String value) {
        this.filterCriteriaId = value;
    }

}
