//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for FulfilmentMethod complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FulfilmentMethod">
 *   &lt;complexContent>
 *     &lt;extension base="{http://domainmodel.pts_fsm.org/2015/10/29/common}FSM.ID">
 *       &lt;sequence>
 *         &lt;element name="FulfilmentMethodTypeId" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID"/>
 *         &lt;element name="Supplier" type="{http://domainmodel.pts_fsm.org/2015/10/29/actors}Supplier" minOccurs="0"/>
 *         &lt;element name="FulfilmentMethodChangeAllowedAfterBooking" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Notification" type="{http://domainmodel.pts_fsm.org/2015/10/29/fulfilment}FulfilmentNotification" maxOccurs="unbounded"/>
 *         &lt;element name="AdditionalInformation" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}AdditionalEntry" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FulfilmentMethod", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/fulfilment", propOrder = {
    "fulfilmentMethodTypeId",
    "supplier",
    "fulfilmentMethodChangeAllowedAfterBooking",
    "notification",
    "additionalInformation"
})
public class FulfilmentMethod
    extends FSMID
{

    @XmlElement(name = "FulfilmentMethodTypeId", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String fulfilmentMethodTypeId;
    @XmlElement(name = "Supplier")
    protected Supplier supplier;
    @XmlElement(name = "FulfilmentMethodChangeAllowedAfterBooking")
    protected Boolean fulfilmentMethodChangeAllowedAfterBooking;
    @XmlElement(name = "Notification", required = true)
    protected List<FulfilmentNotification> notification;
    @XmlElement(name = "AdditionalInformation")
    protected List<AdditionalEntry> additionalInformation;

    /**
     * Gets the value of the fulfilmentMethodTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFulfilmentMethodTypeId() {
        return fulfilmentMethodTypeId;
    }

    /**
     * Sets the value of the fulfilmentMethodTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFulfilmentMethodTypeId(String value) {
        this.fulfilmentMethodTypeId = value;
    }

    /**
     * Gets the value of the supplier property.
     * 
     * @return
     *     possible object is
     *     {@link Supplier }
     *     
     */
    public Supplier getSupplier() {
        return supplier;
    }

    /**
     * Sets the value of the supplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Supplier }
     *     
     */
    public void setSupplier(Supplier value) {
        this.supplier = value;
    }

    /**
     * Gets the value of the fulfilmentMethodChangeAllowedAfterBooking property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFulfilmentMethodChangeAllowedAfterBooking() {
        return fulfilmentMethodChangeAllowedAfterBooking;
    }

    /**
     * Sets the value of the fulfilmentMethodChangeAllowedAfterBooking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFulfilmentMethodChangeAllowedAfterBooking(Boolean value) {
        this.fulfilmentMethodChangeAllowedAfterBooking = value;
    }

    /**
     * Gets the value of the notification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FulfilmentNotification }
     * 
     * 
     */
    public List<FulfilmentNotification> getNotification() {
        if (notification == null) {
            notification = new ArrayList<FulfilmentNotification>();
        }
        return this.notification;
    }

    /**
     * Gets the value of the additionalInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalEntry }
     * 
     * 
     */
    public List<AdditionalEntry> getAdditionalInformation() {
        if (additionalInformation == null) {
            additionalInformation = new ArrayList<AdditionalEntry>();
        }
        return this.additionalInformation;
    }

}
