//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 * 			
 * 
 * <p>Java class for ImmediatePaymentCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImmediatePaymentCondition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Restriction" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}AdditionalEntry" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CardType" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TermsAndConditions" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}GenericTextMessage" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImmediatePaymentCondition", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/payment", propOrder = {
    "restriction",
    "cardType",
    "termsAndConditions"
})
public class ImmediatePaymentCondition {

    @XmlElement(name = "Restriction")
    protected List<AdditionalEntry> restriction;
    @XmlElement(name = "CardType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected List<String> cardType;
    @XmlElement(name = "TermsAndConditions")
    protected List<GenericTextMessage> termsAndConditions;

    /**
     * Gets the value of the restriction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the restriction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRestriction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalEntry }
     * 
     * 
     */
    public List<AdditionalEntry> getRestriction() {
        if (restriction == null) {
            restriction = new ArrayList<AdditionalEntry>();
        }
        return this.restriction;
    }

    /**
     * Gets the value of the cardType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cardType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCardType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCardType() {
        if (cardType == null) {
            cardType = new ArrayList<String>();
        }
        return this.cardType;
    }

    /**
     * Gets the value of the termsAndConditions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the termsAndConditions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTermsAndConditions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenericTextMessage }
     * 
     * 
     */
    public List<GenericTextMessage> getTermsAndConditions() {
        if (termsAndConditions == null) {
            termsAndConditions = new ArrayList<GenericTextMessage>();
        }
        return this.termsAndConditions;
    }

}
