//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for PassengerPreference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PassengerPreference">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="SpecialOrder" type="{http://domainmodel.pts_fsm.org/2015/10/29/tariff}SpecialOrder" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Preference" type="{http://domainmodel.pts_fsm.org/2015/10/29/passenger}Preference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PlaceReference" type="{http://domainmodel.pts_fsm.org/2015/10/29/transportation}PlaceReference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RequestedAncillaryService" type="{http://domainmodel.pts_fsm.org/2015/10/29/offering}RequestedAncillaryService" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RequestedPRMSupport" type="{http://domainmodel.pts_fsm.org/2015/10/29/offering}RequestedPRMSupport" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PassengerPreference", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/passenger", propOrder = {
    "specialOrder",
    "preference",
    "placeReference",
    "requestedAncillaryService",
    "requestedPRMSupport"
})
@XmlSeeAlso({
    OfferingPassengerPreference.class,
    PreBookingPassengerPreference.class
})
public class PassengerPreference {

    @XmlElement(name = "SpecialOrder")
    protected List<SpecialOrder> specialOrder;
    @XmlElement(name = "Preference")
    protected List<Preference> preference;
    @XmlElement(name = "PlaceReference")
    protected List<PlaceReference> placeReference;
    @XmlElement(name = "RequestedAncillaryService")
    protected List<RequestedAncillaryService> requestedAncillaryService;
    @XmlElement(name = "RequestedPRMSupport")
    protected List<RequestedPRMSupport> requestedPRMSupport;

    /**
     * Gets the value of the specialOrder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specialOrder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecialOrder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpecialOrder }
     * 
     * 
     */
    public List<SpecialOrder> getSpecialOrder() {
        if (specialOrder == null) {
            specialOrder = new ArrayList<SpecialOrder>();
        }
        return this.specialOrder;
    }

    /**
     * Gets the value of the preference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the preference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPreference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Preference }
     * 
     * 
     */
    public List<Preference> getPreference() {
        if (preference == null) {
            preference = new ArrayList<Preference>();
        }
        return this.preference;
    }

    /**
     * Gets the value of the placeReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the placeReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlaceReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlaceReference }
     * 
     * 
     */
    public List<PlaceReference> getPlaceReference() {
        if (placeReference == null) {
            placeReference = new ArrayList<PlaceReference>();
        }
        return this.placeReference;
    }

    /**
     * Gets the value of the requestedAncillaryService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestedAncillaryService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequestedAncillaryService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequestedAncillaryService }
     * 
     * 
     */
    public List<RequestedAncillaryService> getRequestedAncillaryService() {
        if (requestedAncillaryService == null) {
            requestedAncillaryService = new ArrayList<RequestedAncillaryService>();
        }
        return this.requestedAncillaryService;
    }

    /**
     * Gets the value of the requestedPRMSupport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestedPRMSupport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequestedPRMSupport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequestedPRMSupport }
     * 
     * 
     */
    public List<RequestedPRMSupport> getRequestedPRMSupport() {
        if (requestedPRMSupport == null) {
            requestedPRMSupport = new ArrayList<RequestedPRMSupport>();
        }
        return this.requestedPRMSupport;
    }

}
