//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import st4rt.convertor.empire.annotation.Query;
import st4rt.convertor.empire.annotation.Query.QueryType;
import st4rt.convertor.empire.annotation.RdfProperty;
import st4rt.convertor.empire.annotation.RdfsClass;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for PlaceReference complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PlaceReference">
 *   &lt;complexContent>
 *     &lt;extension base="{http://domainmodel.pts_fsm.org/2015/10/29/common}FSM.ID">
 *       &lt;sequence minOccurs="0">
 *         &lt;choice>
 *           &lt;element name="SegmentIdRef" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN"/>
 *           &lt;element name="SegmentRef" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="PassengerIdRef" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN"/>
 *           &lt;element name="PassengerRef" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
 *         &lt;/choice>
 *         &lt;element name="PlaceTypeId" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" minOccurs="0"/>
 *         &lt;element name="CoachId" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" minOccurs="0"/>
 *         &lt;element name="CompartmentId" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" minOccurs="0"/>
 *         &lt;element name="PlaceId" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" minOccurs="0"/>
 *         &lt;element name="FloorId" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" minOccurs="0"/>
 *         &lt;element name="WidthPos" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="LengthPos" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CompartmentWidthPos" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CompartmentLengthPos" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="NeighbourPassengerIdRefsList" type="{http://www.w3.org/2001/XMLSchema}NMTOKENS"/>
 *           &lt;element name="NeighbourPassengerRefsList" type="{http://www.w3.org/2001/XMLSchema}IDREFS"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlaceReference", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/transportation", propOrder = {
        "segmentIdRef",
        "segmentRef",
        "passengerIdRef",
        "passengerRef",
        "placeTypeId",
        "coachId",
        "compartmentId",
        "placeId",
        "floorId",
        "widthPos",
        "lengthPos",
        "compartmentWidthPos",
        "compartmentLengthPos",
        "neighbourPassengerIdRefsList",
        "neighbourPassengerRefsList"
})
@RdfsClass("product:Facility")
public class PlaceReference
        extends FSMID
{

    @XmlElement(name = "SegmentIdRef")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String segmentIdRef;

    @XmlElement(name = "SegmentRef")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    @RdfProperty(propertyName="st4rt:referencesTravelEpisode")
    protected Object segmentRef;

    @XmlElement(name = "PassengerIdRef")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String passengerIdRef;

    @XmlElement(name = "PassengerRef")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    @RdfProperty(propertyName ="st4rt:referencesPassenger")
    protected Object passengerRef;

    @XmlElement(name = "PlaceTypeId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String placeTypeId;
    @XmlElement(name = "CoachId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")

    @Query(name="FSM_LW_CoachNumber", outputs= {"coachNo"}, type=QueryType.Lowering)
    @RdfProperty(propertyName="product:hasCoachNo")
    protected String coachId;

    @XmlElement(name = "CompartmentId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String compartmentId;
    @XmlElement(name = "PlaceId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")

    @RdfProperty(propertyName = "product:hasPlaceNo")
    protected String placeId;

    @XmlElement(name = "FloorId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String floorId;
    @XmlElement(name = "WidthPos")
    protected BigDecimal widthPos;
    @XmlElement(name = "LengthPos")
    protected BigDecimal lengthPos;
    @XmlElement(name = "CompartmentWidthPos")
    protected BigDecimal compartmentWidthPos;
    @XmlElement(name = "CompartmentLengthPos")
    protected BigDecimal compartmentLengthPos;
    @XmlList
    @XmlElement(name = "NeighbourPassengerIdRefsList")
    @XmlSchemaType(name = "NMTOKENS")
    protected List<String> neighbourPassengerIdRefsList;
    @XmlList
    @XmlElement(name = "NeighbourPassengerRefsList")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> neighbourPassengerRefsList;

    /**
     * Gets the value of the segmentIdRef property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSegmentIdRef() {
        return segmentIdRef;
    }

    /**
     * Sets the value of the segmentIdRef property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSegmentIdRef(String value) {
        this.segmentIdRef = value;
    }

    /**
     * Gets the value of the segmentRef property.
     *
     * @return
     *     possible object is
     *     {@link Object }
     *
     */
    public Object getSegmentRef() {
        return segmentRef;
    }

    /**
     * Sets the value of the segmentRef property.
     *
     * @param value
     *     allowed object is
     *     {@link Object }
     *
     */
    public void setSegmentRef(Object value) {
        this.segmentRef = value;
    }

    /**
     * Gets the value of the passengerIdRef property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPassengerIdRef() {
        return passengerIdRef;
    }

    /**
     * Sets the value of the passengerIdRef property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPassengerIdRef(String value) {
        this.passengerIdRef = value;
    }

    /**
     * Gets the value of the passengerRef property.
     *
     * @return
     *     possible object is
     *     {@link Object }
     *
     */
    public Object getPassengerRef() {
        return passengerRef;
    }

    /**
     * Sets the value of the passengerRef property.
     *
     * @param value
     *     allowed object is
     *     {@link Object }
     *
     */
    public void setPassengerRef(Object value) {
        this.passengerRef = value;
    }

    /**
     * Gets the value of the placeTypeId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPlaceTypeId() {
        return placeTypeId;
    }

    /**
     * Sets the value of the placeTypeId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPlaceTypeId(String value) {
        this.placeTypeId = value;
    }

    /**
     * Gets the value of the coachId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCoachId() {
        return coachId;
    }

    /**
     * Sets the value of the coachId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCoachId(String value) {
        this.coachId = value;
    }

    /**
     * Gets the value of the compartmentId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCompartmentId() {
        return compartmentId;
    }

    /**
     * Sets the value of the compartmentId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCompartmentId(String value) {
        this.compartmentId = value;
    }

    /**
     * Gets the value of the placeId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPlaceId() {
        return placeId;
    }

    /**
     * Sets the value of the placeId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPlaceId(String value) {
        this.placeId = value;
    }

    /**
     * Gets the value of the floorId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFloorId() {
        return floorId;
    }

    /**
     * Sets the value of the floorId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFloorId(String value) {
        this.floorId = value;
    }

    /**
     * Gets the value of the widthPos property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getWidthPos() {
        return widthPos;
    }

    /**
     * Sets the value of the widthPos property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setWidthPos(BigDecimal value) {
        this.widthPos = value;
    }

    /**
     * Gets the value of the lengthPos property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getLengthPos() {
        return lengthPos;
    }

    /**
     * Sets the value of the lengthPos property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setLengthPos(BigDecimal value) {
        this.lengthPos = value;
    }

    /**
     * Gets the value of the compartmentWidthPos property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getCompartmentWidthPos() {
        return compartmentWidthPos;
    }

    /**
     * Sets the value of the compartmentWidthPos property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setCompartmentWidthPos(BigDecimal value) {
        this.compartmentWidthPos = value;
    }

    /**
     * Gets the value of the compartmentLengthPos property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getCompartmentLengthPos() {
        return compartmentLengthPos;
    }

    /**
     * Sets the value of the compartmentLengthPos property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setCompartmentLengthPos(BigDecimal value) {
        this.compartmentLengthPos = value;
    }

    /**
     * Gets the value of the neighbourPassengerIdRefsList property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the neighbourPassengerIdRefsList property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNeighbourPassengerIdRefsList().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getNeighbourPassengerIdRefsList() {
        if (neighbourPassengerIdRefsList == null) {
            neighbourPassengerIdRefsList = new ArrayList<String>();
        }
        return this.neighbourPassengerIdRefsList;
    }

    /**
     * Gets the value of the neighbourPassengerRefsList property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the neighbourPassengerRefsList property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNeighbourPassengerRefsList().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     *
     *
     */
    public List<Object> getNeighbourPassengerRefsList() {
        if (neighbourPassengerRefsList == null) {
            neighbourPassengerRefsList = new ArrayList<Object>();
        }
        return this.neighbourPassengerRefsList;
    }

}
