//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//

package st4rt.convertor.eu.start.standards.FSM;

import st4rt.convertor.empire.annotation.SupportsRdfId;
import st4rt.convertor.empire.annotation.*;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;

/**
 * 
 * The PreBookRequest message is used in different cases that will impact the
 * content of the message : - It can follows an Offering Process (Offer Request
 * - Offer Response) and create a new Booking - It can follows an Offering
 * Process (Offer Request - Offer Response) and add to an existing Booking - It
 * can initiate a Booking Process within a Direct-Booking Mode Also, the process
 * can use Statefull or Stateless mechanism that also impact the message
 * content.
 * 
 * 
 * <p>
 * Java class for PreBookRequest complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="PreBookRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://servicemodel.pts_fsm.org/2015/10/29/fsm.common.messages}Request">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="BookingIdRef" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" minOccurs="0"/>
 *         &lt;element name="CarrierOfferIdRefsList" type="{http://www.w3.org/2001/XMLSchema}NMTOKENS" minOccurs="0"/>
 *         &lt;element name="CarrierOfferContainer" type="{http://domainmodel.pts_fsm.org/2015/10/29/offering}SaleCarrierOfferContainer" minOccurs="0"/>
 *         &lt;element name="FulfilmentMethod" type="{http://domainmodel.pts_fsm.org/2015/10/29/fulfilment}FulfilmentMethod" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PaymentMode" type="{http://domainmodel.pts_fsm.org/2015/10/29/payment}PaymentMode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PassengerPreference" type="{http://domainmodel.pts_fsm.org/2015/10/29/passenger}PreBookingPassengerPreference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ContactInformation" type="{http://domainmodel.pts_fsm.org/2015/10/29/passenger}ContactInformation" minOccurs="0"/>
 *         &lt;element name="DirectBookingParameters" type="{http://domainmodel.pts_fsm.org/2015/10/29/offering}DirectBookingParameters" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreBookRequest", namespace = "http://servicemodel.pts_fsm.org/2015/10/29/rsp.booking.messages", propOrder = {
		"bookingIdRef", "carrierOfferIdRefsList", "carrierOfferContainer", "fulfilmentMethod", "paymentMode",
		"passengerPreference", "contactInformation", "directBookingParameters" })
@XmlRootElement(name = "PreBookRequest", namespace = "http://servicemodel.pts_fsm.org/2015/10/29/rsp.booking.messages")

@NamedGraph(type = NamedGraph.NamedGraphType.Static)
@Namespaces({ "st4rt", "http://st4rt.eu/ontologies/st4rt#", "it2r",
	"http://it2rail.eu/ontology#", "foaf", "http://xmlns.com/foaf/0.1/#",
		"shopping", "http://www.it2rail.eu/ontology/shopping#",
		"travel", "http://www.it2rail.eu/ontology/travel#",
		"transport", "http://www.it2rail.eu/ontology/transport#",
		"infrastructure", "http://www.it2rail.eu/ontology/infrastructure#",
		"customer", "http://www.it2rail.eu/ontology/customer#",
		"product", "http://www.it2rail.eu/ontology/product#",
		"mobility", "http://www.it2rail.eu/ontology/mobility#",
		"xmlschema", "http://www.w3.org/2001/XMLSchema#"
})
@RdfsClass("st4rt:ProvisionalBookingRequestMessage")
@Queries({
	@Query(name = "FSM_LF_NumberOfPassengers"),
	@Query(name = "FSM_LF_Delete_HasPassenger1"),
	@Query(name = "FSM_LF_Delete_HasPassenger2"),
	@Query(name = "FSM_LF_Product"),
	@Query(name = "FSM_LF_CodingSystem"),
	@Query(name = "FSM_LF_RequestingSystem"),
	@Query(name = "FSM_LF_CallerToTerminal")
	})
public class PreBookRequest
extends Request implements SupportsRdfId {

	@XmlTransient
	private SupportsRdfId mIdSupport = new SupportsRdfIdImpl();

	public RdfKey getRdfId() {
		return mIdSupport.getRdfId();
	}

	public void setRdfId(RdfKey theId) {
		mIdSupport.setRdfId(theId);
	}
	
	@XmlElement(name = "BookingIdRef")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NMTOKEN")
	protected String bookingIdRef;
	@XmlList
	@XmlElement(name = "CarrierOfferIdRefsList")
	@XmlSchemaType(name = "NMTOKENS")
	protected List<String> carrierOfferIdRefsList;

	@XmlElement(name = "CarrierOfferContainer")
	@RdfProperty(propertyName = "travel:hasItineraryOffer")
	protected SaleCarrierOfferContainer carrierOfferContainer;
	
	@XmlElement(name = "FulfilmentMethod")
	protected List<FulfilmentMethod> fulfilmentMethod;
	@XmlElement(name = "PaymentMode")
	protected List<PaymentMode> paymentMode;
	@XmlElement(name = "PassengerPreference")
	protected List<PreBookingPassengerPreference> passengerPreference;

	@XmlElement(name = "ContactInformation")
	protected ContactInformation contactInformation;

	@XmlElement(name = "DirectBookingParameters")
	protected DirectBookingParameters directBookingParameters;

	/**
	 * Gets the value of the bookingIdRef property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBookingIdRef() {
		return bookingIdRef;
	}

	/**
	 * Sets the value of the bookingIdRef property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBookingIdRef(String value) {
		this.bookingIdRef = value;
	}

	/**
	 * Gets the value of the carrierOfferIdRefsList property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the carrierOfferIdRefsList property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCarrierOfferIdRefsList().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getCarrierOfferIdRefsList() {
		if (carrierOfferIdRefsList == null) {
			carrierOfferIdRefsList = new ArrayList<String>();
		}
		return this.carrierOfferIdRefsList;
	}

	/**
	 * Gets the value of the carrierOfferContainer property.
	 * 
	 * @return possible object is {@link SaleCarrierOfferContainer }
	 * 
	 */
	public SaleCarrierOfferContainer getCarrierOfferContainer() {
		return carrierOfferContainer;
	}

	/**
	 * Sets the value of the carrierOfferContainer property.
	 * 
	 * @param value
	 *            allowed object is {@link SaleCarrierOfferContainer }
	 * 
	 */
	public void setCarrierOfferContainer(SaleCarrierOfferContainer value) {
		this.carrierOfferContainer = value;
	}

	/**
	 * Gets the value of the fulfilmentMethod property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the fulfilmentMethod property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFulfilmentMethod().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link FulfilmentMethod }
	 * 
	 * 
	 */
	public List<FulfilmentMethod> getFulfilmentMethod() {
		if (fulfilmentMethod == null) {
			fulfilmentMethod = new ArrayList<FulfilmentMethod>();
		}
		return this.fulfilmentMethod;
	}

	/**
	 * Gets the value of the paymentMode property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the paymentMode property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPaymentMode().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link PaymentMode }
	 * 
	 * 
	 */
	public List<PaymentMode> getPaymentMode() {
		if (paymentMode == null) {
			paymentMode = new ArrayList<PaymentMode>();
		}
		return this.paymentMode;
	}

	/**
	 * Gets the value of the passengerPreference property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the passengerPreference property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPassengerPreference().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link PreBookingPassengerPreference }
	 * 
	 * 
	 */
	public List<PreBookingPassengerPreference> getPassengerPreference() {
		if (passengerPreference == null) {
			passengerPreference = new ArrayList<PreBookingPassengerPreference>();
		}
		return this.passengerPreference;
	}

	/**
	 * Gets the value of the contactInformation property.
	 * 
	 * @return possible object is {@link ContactInformation }
	 * 
	 */
	public ContactInformation getContactInformation() {
		return contactInformation;
	}

	/**
	 * Sets the value of the contactInformation property.
	 * 
	 * @param value
	 *            allowed object is {@link ContactInformation }
	 * 
	 */
	public void setContactInformation(ContactInformation value) {
		this.contactInformation = value;
	}

	/**
	 * Gets the value of the directBookingParameters property.
	 * 
	 * @return possible object is {@link DirectBookingParameters }
	 * 
	 */
	public DirectBookingParameters getDirectBookingParameters() {
		return directBookingParameters;
	}

	/**
	 * Sets the value of the directBookingParameters property.
	 * 
	 * @param value
	 *            allowed object is {@link DirectBookingParameters }
	 * 
	 */
	public void setDirectBookingParameters(DirectBookingParameters value) {
		this.directBookingParameters = value;
	}

}
