//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for PreBookingPassengerPreference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PreBookingPassengerPreference">
 *   &lt;complexContent>
 *     &lt;extension base="{http://domainmodel.pts_fsm.org/2015/10/29/passenger}PassengerPreference">
 *       &lt;sequence minOccurs="0">
 *         &lt;choice>
 *           &lt;element name="PassengerIdRefsList" type="{http://www.w3.org/2001/XMLSchema}NMTOKENS"/>
 *           &lt;element name="PassengerRefsList" type="{http://www.w3.org/2001/XMLSchema}IDREFS"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreBookingPassengerPreference", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/passenger", propOrder = {
    "passengerIdRefsList",
    "passengerRefsList"
})
public class PreBookingPassengerPreference
    extends PassengerPreference
{

    @XmlList
    @XmlElement(name = "PassengerIdRefsList")
    @XmlSchemaType(name = "NMTOKENS")
    protected List<String> passengerIdRefsList;
    @XmlList
    @XmlElement(name = "PassengerRefsList")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> passengerRefsList;

    /**
     * Gets the value of the passengerIdRefsList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the passengerIdRefsList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPassengerIdRefsList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPassengerIdRefsList() {
        if (passengerIdRefsList == null) {
            passengerIdRefsList = new ArrayList<String>();
        }
        return this.passengerIdRefsList;
    }

    /**
     * Gets the value of the passengerRefsList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the passengerRefsList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPassengerRefsList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getPassengerRefsList() {
        if (passengerRefsList == null) {
            passengerRefsList = new ArrayList<Object>();
        }
        return this.passengerRefsList;
    }

}
