//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PreBookingFault complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PreBookingFault">
 *   &lt;complexContent>
 *     &lt;extension base="{http://servicemodel.pts_fsm.org/2015/10/29/fsm.notification.messages}Fault">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="CarrierOffer" type="{http://domainmodel.pts_fsm.org/2015/10/29/offering}SaleCarrierOffer"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreBookingFault", namespace = "http://servicemodel.pts_fsm.org/2015/10/29/fsm.notification.messages", propOrder = {
    "carrierOffer"
})
public class PreBookingFault
    extends Fault
{

    @XmlElement(name = "CarrierOffer")
    protected SaleCarrierOffer carrierOffer;

    /**
     * Gets the value of the carrierOffer property.
     * 
     * @return
     *     possible object is
     *     {@link SaleCarrierOffer }
     *     
     */
    public SaleCarrierOffer getCarrierOffer() {
        return carrierOffer;
    }

    /**
     * Sets the value of the carrierOffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link SaleCarrierOffer }
     *     
     */
    public void setCarrierOffer(SaleCarrierOffer value) {
        this.carrierOffer = value;
    }

}
