//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import st4rt.convertor.empire.annotation.SupportsRdfId;
import st4rt.convertor.empire.annotation.*;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Product complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Product">
 *   &lt;complexContent>
 *     &lt;extension base="{http://domainmodel.pts_fsm.org/2015/10/29/common}FSM.ID">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Description" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}GenericTextMessage" minOccurs="0"/>
 *         &lt;element name="ProductInformation" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}AdditionalEntry" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Code" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="DisplayName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="QualityOfServiceId" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" />
 *       &lt;attribute name="VolatilityIndex" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" />
 *       &lt;attribute name="DirectBookable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Product", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/tariff", propOrder = {
    "description",
    "productInformation"
})
@RdfsClass("product:Product")
@Queries({
        @Query(name = "FSM_LW_ProductInformation", type = Query.QueryType.Lowering),
        @Query(name = "FSM_LW_ServiceQuality", type = Query.QueryType.Lowering)
})
public class Product
    extends FSMID implements SupportsRdfId {

    @XmlTransient
    private SupportsRdfId mIdSupport = new SupportsRdfIdImpl();

    public RdfKey getRdfId() {
        return mIdSupport.getRdfId();
    }

    public void setRdfId(RdfKey theId) {
        mIdSupport.setRdfId(theId);
    }

    @XmlElement(name = "Description")
    protected GenericTextMessage description;
    
    @XmlElement(name = "ProductInformation")
    @RdfProperty(propertyName = "st4rt:hasProductInformation", isList = true)
    protected List<AdditionalEntry> productInformation;
    
    @XmlAttribute(name = "Code")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String code;
    @XmlAttribute(name = "DisplayName")
    protected String displayName;
    @XmlAttribute(name = "QualityOfServiceId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @RdfProperty(links = {
            @Link(propertyName = "product:hasFareProductDescription", nodeType = Link.NodeType.Shared, sharedID = "IDforFareProductDescription"),
            @Link(propertyName = "product:hasServiceQuality", nodeType = Link.NodeType.Shared, sharedID = "IDforServiceQuality")},
            propertyName = "st4rt:hasCVValue")
    protected String qualityOfServiceId;
    @XmlAttribute(name = "VolatilityIndex")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String volatilityIndex;
    @XmlAttribute(name = "DirectBookable")
    protected Boolean directBookable;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link GenericTextMessage }
     *     
     */
    public GenericTextMessage getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericTextMessage }
     *     
     */
    public void setDescription(GenericTextMessage value) {
        this.description = value;
    }

    /**
     * Gets the value of the productInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalEntry }
     * 
     * 
     */
    public List<AdditionalEntry> getProductInformation() {
        if (productInformation == null) {
            productInformation = new ArrayList<AdditionalEntry>();
        }
        return this.productInformation;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the qualityOfServiceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualityOfServiceId() {
        return qualityOfServiceId;
    }

    /**
     * Sets the value of the qualityOfServiceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualityOfServiceId(String value) {
        this.qualityOfServiceId = value;
    }

    /**
     * Gets the value of the volatilityIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolatilityIndex() {
        return volatilityIndex;
    }

    /**
     * Sets the value of the volatilityIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolatilityIndex(String value) {
        this.volatilityIndex = value;
    }

    public Boolean getDirectBookable() {
        return directBookable;
    }

    public void setDirectBookable(Boolean directBookable) {
        this.directBookable = directBookable;
    }
}
