//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Refunding complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Refunding">
 *   &lt;complexContent>
 *     &lt;extension base="{http://domainmodel.pts_fsm.org/2015/10/29/common}FSM.ID">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="HandlingFee" type="{http://domainmodel.pts_fsm.org/2015/10/29/tariff}HandlingFee" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="RefundingFlexibilityLevelId" use="required" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Refunding", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/tariff", propOrder = {
    "handlingFee"
})
public class Refunding
    extends FSMID
{

    @XmlElement(name = "HandlingFee")
    protected List<HandlingFee> handlingFee;
    @XmlAttribute(name = "RefundingFlexibilityLevelId", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refundingFlexibilityLevelId;

    /**
     * Gets the value of the handlingFee property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the handlingFee property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHandlingFee().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HandlingFee }
     * 
     * 
     */
    public List<HandlingFee> getHandlingFee() {
        if (handlingFee == null) {
            handlingFee = new ArrayList<HandlingFee>();
        }
        return this.handlingFee;
    }

    /**
     * Gets the value of the refundingFlexibilityLevelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefundingFlexibilityLevelId() {
        return refundingFlexibilityLevelId;
    }

    /**
     * Sets the value of the refundingFlexibilityLevelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefundingFlexibilityLevelId(String value) {
        this.refundingFlexibilityLevelId = value;
    }

}
