//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.*;


/**
 * complexType which serves as a base for all reply messages.
 * 
 * <p>Java class for Response complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Response">
 *   &lt;complexContent>
 *     &lt;extension base="{http://servicemodel.pts_fsm.org/2015/10/29/fsm.common.messages}ResponseRequest">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Reflection" type="{http://servicemodel.pts_fsm.org/2015/10/29/fsm.common.messages}Reflection" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Response", namespace = "http://servicemodel.pts_fsm.org/2015/10/29/fsm.common.messages", propOrder = {
    "reflection"
})
@XmlSeeAlso({
    PreBookResponse.class,
    ConfirmBookingResponse.class,
    RetrieveBookingResponse.class
})
public abstract class Response
    extends ResponseRequest
{

    @XmlElement(name = "Reflection")
    protected Reflection reflection;

    /**
     * Gets the value of the reflection property.
     * 
     * @return
     *     possible object is
     *     {@link Reflection }
     *     
     */
    public Reflection getReflection() {
        return reflection;
    }

    /**
     * Sets the value of the reflection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reflection }
     *     
     */
    public void setReflection(Reflection value) {
        this.reflection = value;
    }

}
