//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 				The distributor shall be able to retrieve the latest booking information from the Rail Service Provider.
 * 				The booking contains the After-Sales rules defined for each CarrierServiceItem (CarrierServiceItem.AfterSalesConditions).
 * 			
 * 
 * <p>Java class for RetrieveBookingRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RetrieveBookingRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://servicemodel.pts_fsm.org/2015/10/29/fsm.common.messages}Request">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="BookingIdRef" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN"/>
 *         &lt;element name="RetrieveAllItems" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RetrieveBookingRequest", namespace = "http://servicemodel.pts_fsm.org/2015/10/29/rsp.booking.messages", propOrder = {
    "bookingIdRef",
    "retrieveAllItems"
})
public class RetrieveBookingRequest
    extends Request
{

    @XmlElement(name = "BookingIdRef")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String bookingIdRef;
    @XmlElement(name = "RetrieveAllItems")
    protected Boolean retrieveAllItems;

    /**
     * Gets the value of the bookingIdRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingIdRef() {
        return bookingIdRef;
    }

    /**
     * Sets the value of the bookingIdRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingIdRef(String value) {
        this.bookingIdRef = value;
    }

    /**
     * Gets the value of the retrieveAllItems property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRetrieveAllItems() {
        return retrieveAllItems;
    }

    /**
     * Sets the value of the retrieveAllItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRetrieveAllItems(Boolean value) {
        this.retrieveAllItems = value;
    }

}
