//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				The response to a RetrieveBookingRequest is a "Booking" element.
 * 			
 * 
 * <p>Java class for RetrieveBookingResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RetrieveBookingResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://servicemodel.pts_fsm.org/2015/10/29/fsm.common.messages}Response">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Booking" type="{http://domainmodel.pts_fsm.org/2015/10/29/booking}Booking"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RetrieveBookingResponse", namespace = "http://servicemodel.pts_fsm.org/2015/10/29/rsp.booking.messages", propOrder = {
    "booking"
})
public class RetrieveBookingResponse
    extends Response
{

    @XmlElement(name = "Booking")
    protected Booking booking;

    /**
     * Gets the value of the booking property.
     * 
     * @return
     *     possible object is
     *     {@link Booking }
     *     
     */
    public Booking getBooking() {
        return booking;
    }

    /**
     * Sets the value of the booking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Booking }
     *     
     */
    public void setBooking(Booking value) {
        this.booking = value;
    }

}
