//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import st4rt.convertor.empire.annotation.SupportsRdfId;
import st4rt.convertor.empire.annotation.RdfProperty;
import st4rt.convertor.empire.annotation.RdfsClass;
import st4rt.convertor.empire.annotation.SupportsRdfIdImpl;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for SaleCarrierOfferContainer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SaleCarrierOfferContainer">
 *   &lt;complexContent>
 *     &lt;extension base="{http://domainmodel.pts_fsm.org/2015/10/29/offering}CarrierOfferContainer">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="CarrierOffer" type="{http://domainmodel.pts_fsm.org/2015/10/29/offering}SaleCarrierOffer" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SaleCarrierOfferContainer", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/offering", propOrder = {
    "carrierOffer"
})
@RdfsClass("shopping:ItineraryOffer")
public class SaleCarrierOfferContainer
    extends CarrierOfferContainer implements SupportsRdfId {

    @XmlTransient
    private SupportsRdfId mIdSupport = new SupportsRdfIdImpl();

    public RdfKey getRdfId() {
        return mIdSupport.getRdfId();
    }

    public void setRdfId(RdfKey theId) {
        mIdSupport.setRdfId(theId);
    }

    @XmlElement(name = "CarrierOffer")
    @RdfProperty(propertyName = "st4rt:hasItineraryOfferItem", isList=true)
    protected List<SaleCarrierOffer> carrierOffer;

    /**
     * Gets the value of the carrierOffer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the carrierOffer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCarrierOffer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SaleCarrierOffer }
     * 
     * 
     */
    public List<SaleCarrierOffer> getCarrierOffer() {
        if (carrierOffer == null) {
            carrierOffer = new ArrayList<SaleCarrierOffer>();
        }
        return this.carrierOffer;
    }

}
