//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for SalesCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SalesCondition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://domainmodel.pts_fsm.org/2015/10/29/common}FSM.ID">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="VehicleBindingType" type="{http://domainmodel.pts_fsm.org/2015/10/29/tariff}AllowedVehicles" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SalesConditionText" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}GenericTextMessage" minOccurs="0"/>
 *         &lt;element name="ImmediatePaymentCondition" type="{http://domainmodel.pts_fsm.org/2015/10/29/payment}ImmediatePaymentCondition" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Open" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ReservationRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ImmediatePaymentAvailability" type="{http://domainmodel.pts_fsm.org/2015/10/29/payment}ImmediatePaymentAvailability" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SalesCondition", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/tariff", propOrder = {
    "vehicleBindingType",
    "salesConditionText",
    "immediatePaymentCondition"
})
public class SalesCondition
    extends FSMID
{

    @XmlElement(name = "VehicleBindingType")
    protected List<AllowedVehicles> vehicleBindingType;
    @XmlElement(name = "SalesConditionText")
    protected GenericTextMessage salesConditionText;
    @XmlElement(name = "ImmediatePaymentCondition")
    protected ImmediatePaymentCondition immediatePaymentCondition;
    @XmlAttribute(name = "Open")
    protected Boolean open;
    @XmlAttribute(name = "ReservationRequired")
    protected Boolean reservationRequired;
    @XmlAttribute(name = "ImmediatePaymentAvailability")
    protected ImmediatePaymentAvailability immediatePaymentAvailability;

    /**
     * Gets the value of the vehicleBindingType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vehicleBindingType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVehicleBindingType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AllowedVehicles }
     * 
     * 
     */
    public List<AllowedVehicles> getVehicleBindingType() {
        if (vehicleBindingType == null) {
            vehicleBindingType = new ArrayList<AllowedVehicles>();
        }
        return this.vehicleBindingType;
    }

    /**
     * Gets the value of the salesConditionText property.
     * 
     * @return
     *     possible object is
     *     {@link GenericTextMessage }
     *     
     */
    public GenericTextMessage getSalesConditionText() {
        return salesConditionText;
    }

    /**
     * Sets the value of the salesConditionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericTextMessage }
     *     
     */
    public void setSalesConditionText(GenericTextMessage value) {
        this.salesConditionText = value;
    }

    /**
     * Gets the value of the immediatePaymentCondition property.
     * 
     * @return
     *     possible object is
     *     {@link ImmediatePaymentCondition }
     *     
     */
    public ImmediatePaymentCondition getImmediatePaymentCondition() {
        return immediatePaymentCondition;
    }

    /**
     * Sets the value of the immediatePaymentCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImmediatePaymentCondition }
     *     
     */
    public void setImmediatePaymentCondition(ImmediatePaymentCondition value) {
        this.immediatePaymentCondition = value;
    }

    /**
     * Gets the value of the open property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOpen() {
        return open;
    }

    /**
     * Sets the value of the open property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOpen(Boolean value) {
        this.open = value;
    }

    /**
     * Gets the value of the reservationRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReservationRequired() {
        return reservationRequired;
    }

    /**
     * Sets the value of the reservationRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReservationRequired(Boolean value) {
        this.reservationRequired = value;
    }

    /**
     * Gets the value of the immediatePaymentAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link ImmediatePaymentAvailability }
     *     
     */
    public ImmediatePaymentAvailability getImmediatePaymentAvailability() {
        return immediatePaymentAvailability;
    }

    /**
     * Sets the value of the immediatePaymentAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImmediatePaymentAvailability }
     *     
     */
    public void setImmediatePaymentAvailability(ImmediatePaymentAvailability value) {
        this.immediatePaymentAvailability = value;
    }

}
