//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for SearchCriteria complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchCriteria">
 *   &lt;complexContent>
 *     &lt;extension base="{http://domainmodel.pts_fsm.org/2015/10/29/common}FSM.ID">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="FilterCriteria" type="{http://domainmodel.pts_fsm.org/2015/10/29/offering}FilterCriteria" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PlaceReservationFeasible" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Product" type="{http://domainmodel.pts_fsm.org/2015/10/29/tariff}Product" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PaymentMode" type="{http://domainmodel.pts_fsm.org/2015/10/29/payment}PaymentMode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PreferenceLevel" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchCriteria", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/offering", propOrder = {
    "filterCriteria",
    "placeReservationFeasible",
    "product",
    "paymentMode",
    "preferenceLevel"
})
public class SearchCriteria
    extends FSMID
{

    @XmlElement(name = "FilterCriteria")
    protected List<FilterCriteria> filterCriteria;
    @XmlElement(name = "PlaceReservationFeasible")
    protected Boolean placeReservationFeasible;
    @XmlElement(name = "Product")
    protected List<Product> product;
    @XmlElement(name = "PaymentMode")
    protected List<PaymentMode> paymentMode;
    @XmlElement(name = "PreferenceLevel")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String preferenceLevel;

    /**
     * Gets the value of the filterCriteria property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filterCriteria property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilterCriteria().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FilterCriteria }
     * 
     * 
     */
    public List<FilterCriteria> getFilterCriteria() {
        if (filterCriteria == null) {
            filterCriteria = new ArrayList<FilterCriteria>();
        }
        return this.filterCriteria;
    }

    /**
     * Gets the value of the placeReservationFeasible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlaceReservationFeasible() {
        return placeReservationFeasible;
    }

    /**
     * Sets the value of the placeReservationFeasible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlaceReservationFeasible(Boolean value) {
        this.placeReservationFeasible = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the product property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProduct().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Product }
     * 
     * 
     */
    public List<Product> getProduct() {
        if (product == null) {
            product = new ArrayList<Product>();
        }
        return this.product;
    }

    /**
     * Gets the value of the paymentMode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentMode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentMode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentMode }
     * 
     * 
     */
    public List<PaymentMode> getPaymentMode() {
        if (paymentMode == null) {
            paymentMode = new ArrayList<PaymentMode>();
        }
        return this.paymentMode;
    }

    /**
     * Gets the value of the preferenceLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferenceLevel() {
        return preferenceLevel;
    }

    /**
     * Sets the value of the preferenceLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferenceLevel(String value) {
        this.preferenceLevel = value;
    }

}
