//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ServiceRelease complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceRelease">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ReleaseTypeId" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" />
 *       &lt;attribute name="ReleaseFrom" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ReleaseTo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceRelease")
public class ServiceRelease {

    @XmlAttribute(name = "ReleaseTypeId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String releaseTypeId;
    @XmlAttribute(name = "ReleaseFrom")
    protected String releaseFrom;
    @XmlAttribute(name = "ReleaseTo")
    protected String releaseTo;

    /**
     * Gets the value of the releaseTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReleaseTypeId() {
        return releaseTypeId;
    }

    /**
     * Sets the value of the releaseTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReleaseTypeId(String value) {
        this.releaseTypeId = value;
    }

    /**
     * Gets the value of the releaseFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReleaseFrom() {
        return releaseFrom;
    }

    /**
     * Sets the value of the releaseFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReleaseFrom(String value) {
        this.releaseFrom = value;
    }

    /**
     * Gets the value of the releaseTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReleaseTo() {
        return releaseTo;
    }

    /**
     * Sets the value of the releaseTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReleaseTo(String value) {
        this.releaseTo = value;
    }

}
