//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ServiceBehavior complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceBehavior">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="SecurityLevelId" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" minOccurs="0"/>
 *         &lt;element name="ProtectionLevelId" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" minOccurs="0"/>
 *         &lt;element name="SessionModeId" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" minOccurs="0"/>
 *         &lt;element name="Security" type="{http://servicemodel.pts_fsm.org/2015/10/29/fsm.common.headers}Security" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceBehavior", propOrder = {
    "securityLevelId",
    "protectionLevelId",
    "sessionModeId",
    "security"
})
public class ServiceBehavior {

    @XmlElement(name = "SecurityLevelId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String securityLevelId;
    @XmlElement(name = "ProtectionLevelId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String protectionLevelId;
    @XmlElement(name = "SessionModeId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String sessionModeId;
    @XmlElement(name = "Security")
    protected Security security;

    /**
     * Gets the value of the securityLevelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityLevelId() {
        return securityLevelId;
    }

    /**
     * Sets the value of the securityLevelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityLevelId(String value) {
        this.securityLevelId = value;
    }

    /**
     * Gets the value of the protectionLevelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtectionLevelId() {
        return protectionLevelId;
    }

    /**
     * Sets the value of the protectionLevelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtectionLevelId(String value) {
        this.protectionLevelId = value;
    }

    /**
     * Gets the value of the sessionModeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionModeId() {
        return sessionModeId;
    }

    /**
     * Sets the value of the sessionModeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionModeId(String value) {
        this.sessionModeId = value;
    }

    /**
     * Gets the value of the security property.
     * 
     * @return
     *     possible object is
     *     {@link Security }
     *     
     */
    public Security getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *     allowed object is
     *     {@link Security }
     *     
     */
    public void setSecurity(Security value) {
        this.security = value;
    }

}
