//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Supplier complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Supplier">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="AddresseeId" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" />
 *       &lt;attribute name="BusinessRoleIdType" type="{http://domainmodel.pts_fsm.org/2015/10/29/common}MasterData.GUID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Supplier", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/actors")
public class Supplier {

    @XmlAttribute(name = "AddresseeId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String addresseeId;
    @XmlAttribute(name = "BusinessRoleIdType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String businessRoleIdType;

    /**
     * Gets the value of the addresseeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddresseeId() {
        return addresseeId;
    }

    /**
     * Sets the value of the addresseeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddresseeId(String value) {
        this.addresseeId = value;
    }

    /**
     * Gets the value of the businessRoleIdType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessRoleIdType() {
        return businessRoleIdType;
    }

    /**
     * Sets the value of the businessRoleIdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessRoleIdType(String value) {
        this.businessRoleIdType = value;
    }

}
