//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.28 at 11:43:51 AM CEST 
//


package st4rt.convertor.eu.start.standards.FSM;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ValidityArea complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValidityArea">
 *   &lt;complexContent>
 *     &lt;extension base="{http://domainmodel.pts_fsm.org/2015/10/29/common}FSM.ID">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Area" type="{http://domainmodel.pts_fsm.org/2015/10/29/tariff}Area" minOccurs="0"/>
 *         &lt;element name="AlternativePath" type="{http://domainmodel.pts_fsm.org/2015/10/29/tariff}AlternativePath" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TrailingArea" type="{http://domainmodel.pts_fsm.org/2015/10/29/tariff}Area" minOccurs="0"/>
 *         &lt;element name="LeadingArea" type="{http://domainmodel.pts_fsm.org/2015/10/29/tariff}Area" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValidityArea", namespace = "http://domainmodel.pts_fsm.org/2015/10/29/tariff", propOrder = {
    "area",
    "alternativePath",
    "trailingArea",
    "leadingArea"
})
public class ValidityArea
    extends FSMID
{

    @XmlElement(name = "Area")
    protected Area area;
    @XmlElement(name = "AlternativePath")
    protected List<AlternativePath> alternativePath;
    @XmlElement(name = "TrailingArea")
    protected Area trailingArea;
    @XmlElement(name = "LeadingArea")
    protected Area leadingArea;

    /**
     * Gets the value of the area property.
     * 
     * @return
     *     possible object is
     *     {@link Area }
     *     
     */
    public Area getArea() {
        return area;
    }

    /**
     * Sets the value of the area property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area }
     *     
     */
    public void setArea(Area value) {
        this.area = value;
    }

    /**
     * Gets the value of the alternativePath property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alternativePath property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlternativePath().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AlternativePath }
     * 
     * 
     */
    public List<AlternativePath> getAlternativePath() {
        if (alternativePath == null) {
            alternativePath = new ArrayList<AlternativePath>();
        }
        return this.alternativePath;
    }

    /**
     * Gets the value of the trailingArea property.
     * 
     * @return
     *     possible object is
     *     {@link Area }
     *     
     */
    public Area getTrailingArea() {
        return trailingArea;
    }

    /**
     * Sets the value of the trailingArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area }
     *     
     */
    public void setTrailingArea(Area value) {
        this.trailingArea = value;
    }

    /**
     * Gets the value of the leadingArea property.
     * 
     * @return
     *     possible object is
     *     {@link Area }
     *     
     */
    public Area getLeadingArea() {
        return leadingArea;
    }

    /**
     * Sets the value of the leadingArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area }
     *     
     */
    public void setLeadingArea(Area value) {
        this.leadingArea = value;
    }

}
